export interface Exercise {
  id: string;
  name: string;
  muscle_group: string;
  secondary_muscles: string[];
  equipment: string;
  difficulty: "Anfänger" | "Mittel" | "Fortgeschritten";
  description: string;
  steps: string[];
  tips: string[];
  calories_per_minute: number;
}

export const EXERCISES: Exercise[] = [
  // BRUST
  {
    id: "bench-press",
    name: "Bankdrücken",
    muscle_group: "Brust",
    secondary_muscles: ["Trizeps", "Schultern"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Die Königsübung für die Brust — maximaler Muskelaufbau mit freiem Gewicht.",
    steps: [
      "Lege dich flach auf die Bank, Augen unter der Stange.",
      "Füße flach auf dem Boden, Rücken leicht gewölbt.",
      "Griffbreite etwas breiter als Schulterbreite.",
      "Stange abnehmen, senkrecht über der Brust halten.",
      "Kontrolliert absenken bis die Stange die Brust berührt.",
      "Explosiv nach oben drücken bis Arme fast gestreckt.",
    ],
    tips: [
      "Daumen immer um die Stange (kein falscher Griff).",
      "Ellenbogen nicht komplett verriegeln oben.",
      "Schulterblätter zusammenziehen und zur Bank drücken.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "push-up",
    name: "Liegestütz",
    muscle_group: "Brust",
    secondary_muscles: ["Trizeps", "Schultern", "Core"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Die beste Körpergewichtsübung für die Brust — überall und ohne Equipment.",
    steps: [
      "Hände schulterbreit auf dem Boden, Finger zeigen leicht nach außen.",
      "Körper bildet eine gerade Linie von Kopf bis Ferse.",
      "Core anspannen, Hüfte nicht hängen lassen.",
      "Absenken bis Brust fast den Boden berührt.",
      "Explosiv hochdrücken.",
    ],
    tips: [
      "Ellenbogen 45° zum Körper halten — nicht ausflaren.",
      "Knie-Variante für Anfänger erlaubt.",
      "Hände breiter = mehr Brustanteil.",
    ],
    calories_per_minute: 7,
  },
  {
    id: "cable-fly",
    name: "Kabelfliegende",
    muscle_group: "Brust",
    secondary_muscles: ["Schultern"],
    equipment: "Kabelzug",
    difficulty: "Mittel",
    description: "Isolationsübung für maximale Dehnung und Kontraktion der Brustmuskeln.",
    steps: [
      "Kabel auf Schulterhöhe einstellen, in die Mitte stellen.",
      "Einen Schritt nach vorne treten, Griffe in beide Hände.",
      "Leicht gebeugte Arme, Rumpf angespannt.",
      "Arme vor der Brust zusammenführen.",
      "Kontrolliert zurück in die Ausgangsposition.",
    ],
    tips: [
      "Leichte Beugung im Ellenbogen halten.",
      "Am Ende kurz einhalten und Brust anspannen.",
    ],
    calories_per_minute: 6,
  },
  {
    id: "dips-chest",
    name: "Dips (Brust)",
    muscle_group: "Brust",
    secondary_muscles: ["Trizeps", "Schultern"],
    equipment: "Dip-Stangen",
    difficulty: "Mittel",
    description: "Compound-Übung mit dem Körpergewicht — Fokus auf untere Brust.",
    steps: [
      "Auf Dip-Stangen hochdrücken, Arme gestreckt.",
      "Körper leicht nach vorne neigen (mehr Brust).",
      "Kontrolliert absenken bis Ellenbogen 90° gebeugt.",
      "Hochdrücken, kurz einhalten.",
    ],
    tips: [
      "Je mehr Vorneigung, desto mehr Brust.",
      "Für Anfänger: Band zur Unterstützung nutzen.",
    ],
    calories_per_minute: 9,
  },
  // RÜCKEN
  {
    id: "pull-up",
    name: "Klimmzug",
    muscle_group: "Rücken",
    secondary_muscles: ["Bizeps", "Schultern"],
    equipment: "Klimmzugstange",
    difficulty: "Mittel",
    description: "Die beste Rückenübung mit dem eigenen Körpergewicht.",
    steps: [
      "Stange im Obergriff (Hände zeigen weg), schulterbreit.",
      "Hängen mit gestreckten Armen.",
      "Schulterblätter zusammenziehen, dann hochziehen.",
      "Kinn über die Stange bringen.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Mit Schulterblättern starten, nicht mit den Armen.",
      "Körper leicht nach hinten neigen.",
      "Band für Assistenz nutzen wenn nötig.",
    ],
    calories_per_minute: 10,
  },
  {
    id: "deadlift",
    name: "Kreuzheben",
    muscle_group: "Rücken",
    secondary_muscles: ["Gesäß", "Hamstrings", "Core", "Trapez"],
    equipment: "Langhantel",
    difficulty: "Fortgeschritten",
    description: "Die mächtigste Grundübung — trainiert fast alle Muskelgruppen gleichzeitig.",
    steps: [
      "Stange über den Mittelfuß, Füße hüftbreit.",
      "Hüfte schieben, Stange greifen schulterbreit.",
      "Brust raus, Rücken gerade, Core anspannen.",
      "Stange nah am Körper halten, gleichzeitig Beine strecken und Hüfte nach vorne.",
      "Oben: Hüfte durchstrecken, Schultern zurück.",
      "Stange kontrolliert absenken.",
    ],
    tips: [
      "Rücken immer gerade — niemals runden!",
      "Mit leichtem Gewicht beginnen und Technik üben.",
      "Stange während der ganzen Bewegung am Körper halten.",
    ],
    calories_per_minute: 12,
  },
  {
    id: "lat-pulldown",
    name: "Latzug",
    muscle_group: "Rücken",
    secondary_muscles: ["Bizeps"],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Einsteigerfreundliche Alternative zum Klimmzug — Gewicht frei wählbar.",
    steps: [
      "Auf dem Latzug-Gerät Platz nehmen, Oberschenkel fixieren.",
      "Stange im breiten Obergriff fassen.",
      "Oberkörper leicht zurücklehnen.",
      "Stange zur Brust ziehen, Ellenbogen nach unten.",
      "Kontrolliert wieder strecken.",
    ],
    tips: [
      "Schulterblätter beim Ziehen zusammenführen.",
      "Nicht mit Schwung ziehen.",
    ],
    calories_per_minute: 7,
  },
  {
    id: "rowing",
    name: "Rudern mit Langhantel",
    muscle_group: "Rücken",
    secondary_muscles: ["Bizeps", "Core"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Horizontale Zugbewegung für mittleren und oberen Rücken.",
    steps: [
      "Hüftbreiter Stand, Langhantel aufheben.",
      "Rumpf nach vorne neigen (ca. 45°), Rücken gerade.",
      "Stange zum Bauchnabel ziehen, Ellenbogen nach hinten.",
      "Schulterblätter zusammendrücken.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Nicht mit dem Rücken schwingen.",
      "Stange bleibt nah am Körper.",
    ],
    calories_per_minute: 9,
  },
  // SCHULTERN
  {
    id: "overhead-press",
    name: "Schulterdrücken",
    muscle_group: "Schultern",
    secondary_muscles: ["Trizeps", "Trapez"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Die Grundübung für volle Schultermuskeln.",
    steps: [
      "Stand oder Sitzen, Langhantel vor der Brust auf Schulterhöhe.",
      "Griff etwas breiter als Schultern.",
      "Stange gerade nach oben drücken.",
      "Oben kurz einhalten.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Core die ganze Zeit angespannt.",
      "Kopf leicht zurückneigen wenn Stange vorbeigeht.",
      "Nicht im Hohlkreuz stehen.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "lateral-raise",
    name: "Seitheben",
    muscle_group: "Schultern",
    secondary_muscles: [],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Isolationsübung für breite, runde Schultern.",
    steps: [
      "Kurzhanteln in beide Hände, Arme hängen neben dem Körper.",
      "Leichte Beugung im Ellenbogen.",
      "Arme seitlich auf Schulterhöhe heben.",
      "Kurz halten, kontrolliert absenken.",
    ],
    tips: [
      "Kleinfinger leicht höher als Daumen (wie ausschütten).",
      "Nicht mit Schwung arbeiten.",
      "Lieber leicht als zu schwer.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "face-pull",
    name: "Face Pulls",
    muscle_group: "Schultern",
    secondary_muscles: ["Trapez", "Rotatorenmanschette"],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Unverzichtbar für Schultergesundheit und hintere Schulter.",
    steps: [
      "Kabelzug auf Kopfhöhe, Seilgriff befestigen.",
      "Einen Schritt zurücktreten.",
      "Seil zum Gesicht ziehen, Ellenbogen nach außen oben.",
      "Kontrolliert zurück.",
    ],
    tips: [
      "Tägliche Übung für gesunde Schultern.",
      "Mehr Wiederholungen als schweres Gewicht.",
    ],
    calories_per_minute: 5,
  },
  // ARME
  {
    id: "bicep-curl",
    name: "Bizeps-Curl",
    muscle_group: "Bizeps",
    secondary_muscles: [],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Die klassische Arm-Übung — isoliert den Bizeps perfekt.",
    steps: [
      "Kurzhanteln in beide Hände, Oberarme am Körper.",
      "Langsam hochcurlen, Ellenbogen bleibt ruhig.",
      "Oben einhalten und Bizeps anspannen.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Ellenbogen nicht nach vorne schwingen.",
      "Volle Bewegungsamplitude nutzen.",
      "Abwechselnd oder gleichzeitig.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "tricep-pushdown",
    name: "Trizeps-Pushdown",
    muscle_group: "Trizeps",
    secondary_muscles: [],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Effektivste Isolation für alle drei Trizeps-Köpfe.",
    steps: [
      "Kabelzug auf Kopfhöhe, Seilgriff oder gerades Griffstück.",
      "Ellenbogen nah am Körper fixieren.",
      "Unterarme nach unten drücken bis Arme gestreckt.",
      "Kurz halten, kontrolliert zurück.",
    ],
    tips: [
      "Ellenbogen nie bewegen.",
      "Am tiefsten Punkt Trizeps maximal anspannen.",
    ],
    calories_per_minute: 5,
  },
  // BEINE
  {
    id: "squat",
    name: "Kniebeuge",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß", "Core", "Rücken"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Die Königin der Beinübungen — baut Masse und Kraft wie keine andere.",
    steps: [
      "Stange auf dem oberen Rücken (nicht Nacken).",
      "Füße schulterbreit, Zehen leicht nach außen.",
      "Tief einatmen, Core anspannen.",
      "Hüfte nach hinten und unten — wie auf Stuhl setzen.",
      "Knie in Zehenrichtung drücken.",
      "Mindestens parallel, Rücken gerade.",
      "Explosiv hochdrücken.",
    ],
    tips: [
      "Fersen immer am Boden.",
      "Knie nicht nach innen fallen lassen.",
      "Tiefer ist besser — volle Amplitude.",
    ],
    calories_per_minute: 11,
  },
  {
    id: "leg-press",
    name: "Beinpresse",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß"],
    equipment: "Maschine",
    difficulty: "Anfänger",
    description: "Rückenfreundliche Alternative zur Kniebeuge.",
    steps: [
      "Auf der Beinpresse Platz nehmen, Füße schulterbreit auf der Plattform.",
      "Sicherungen lösen.",
      "Knie kontrolliert zur Brust beugen.",
      "Nicht ganz strecken (Knie nicht einrasten).",
    ],
    tips: [
      "Füße höher = mehr Gesäß und Hamstrings.",
      "Füße tiefer = mehr Quadrizeps.",
    ],
    calories_per_minute: 9,
  },
  {
    id: "lunge",
    name: "Ausfallschritt",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß", "Core"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Unilaterale Beinübung für Balance, Stabilität und Muskelaufbau.",
    steps: [
      "Aufrechter Stand, Hände in der Hüfte oder Kurzhanteln.",
      "Großen Schritt nach vorne machen.",
      "Hinteres Knie fast zum Boden bringen.",
      "Vorderes Knie bleibt über dem Fuß.",
      "Abdrücken und zurück in Ausgangsposition.",
    ],
    tips: [
      "Rumpf gerade halten.",
      "Vorderes Knie nicht über die Zehen.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "romanian-deadlift",
    name: "Rumänisches Kreuzheben",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß", "Rücken"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Beste Übung für Hamstrings und Gesäß — maximale Dehnung.",
    steps: [
      "Langhantel vor dem Körper halten, Füße hüftbreit.",
      "Hüfte nach hinten schieben, Rücken gerade.",
      "Stange nah am Körper an den Beinen heruntergleiten lassen.",
      "Bis zur Dehnung im hinteren Oberschenkel.",
      "Hüfte nach vorne — zurück in Startposition.",
    ],
    tips: [
      "Knie leicht gebeugt.",
      "Dehnung spüren, nicht tiefer als nötig.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "calf-raise",
    name: "Wadenheben",
    muscle_group: "Beine",
    secondary_muscles: [],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Isoliert die Waden — oft unterschätzt aber wichtig.",
    steps: [
      "Auf einer Stufe oder dem Boden stehen.",
      "Fersen heben so hoch wie möglich.",
      "2 Sekunden oben halten.",
      "Tief absenken für maximale Dehnung.",
    ],
    tips: [
      "Langsame, kontrollierte Bewegung.",
      "Volle Amplitude — auch tief gehen.",
    ],
    calories_per_minute: 5,
  },
  // GESÄSS
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    muscle_group: "Gesäß",
    secondary_muscles: ["Hamstrings", "Core"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Die effektivste Übung für maximale Gesäß-Aktivierung.",
    steps: [
      "Oberer Rücken auf einer Bank, Langhantel auf den Hüften.",
      "Füße hüftbreit, Knie 90°.",
      "Hüfte nach oben drücken bis Körper gerade.",
      "Gesäß oben maximal anspannen.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Kinn zur Brust halten.",
      "Oben kurz pausieren und Gesäß pressen.",
      "Füße etwas weiter vorne = mehr Gluteus.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    muscle_group: "Gesäß",
    secondary_muscles: ["Hamstrings"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Einsteigerversion des Hip Thrust — überall ohne Equipment.",
    steps: [
      "Rücken auf dem Boden, Knie angewinkelt.",
      "Füße flach auf dem Boden, hüftbreit.",
      "Hüfte hochdrücken bis Schultern-Hüfte-Knie in einer Linie.",
      "Gesäß anspannen und 2 Sek halten.",
      "Absenken ohne abzulegen.",
    ],
    tips: [
      "Mit einbeiniger Variante steigern.",
      "Widerstandsband für mehr Intensität.",
    ],
    calories_per_minute: 5,
  },
  // CORE
  {
    id: "plank",
    name: "Planke",
    muscle_group: "Core",
    secondary_muscles: ["Schultern", "Gesäß"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Die effektivste isometrische Core-Übung.",
    steps: [
      "Unterarme auf dem Boden, Ellenbogen unter den Schultern.",
      "Körper bildet eine gerade Linie.",
      "Gesäß nicht heben oder senken.",
      "Tief atmen, Position halten.",
    ],
    tips: [
      "Bauch aktiv einziehen.",
      "Gesäß leicht anspannen.",
      "Zeit langsam steigern.",
    ],
    calories_per_minute: 4,
  },
  {
    id: "crunch",
    name: "Crunch",
    muscle_group: "Core",
    secondary_muscles: [],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Klassische Bauchübung für den oberen Bereich.",
    steps: [
      "Rücken auf dem Boden, Knie angewinkelt.",
      "Hände locker hinter dem Kopf (nicht ziehen).",
      "Oberkörper vom Boden abheben — nur bis Schulterblätter frei sind.",
      "Bauch anspannen, nicht mit Schwung.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Nacken entspannt lassen.",
      "Kleine Bewegung — aber bewusst.",
    ],
    calories_per_minute: 4,
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    muscle_group: "Core",
    secondary_muscles: ["Schräge Bauchmuskeln"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Rotationsbewegung für Schräge Bauchmuskeln.",
    steps: [
      "Sitzen, Oberkörper leicht zurückgelehnt.",
      "Füße vom Boden heben (oder auf dem Boden lassen).",
      "Hände zusammen, abwechselnd links und rechts rotieren.",
    ],
    tips: [
      "Medizinball oder Kurzhantel für mehr Intensität.",
      "Kontrolliert rotieren, nicht schwingen.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "leg-raise",
    name: "Beinheben",
    muscle_group: "Core",
    secondary_muscles: ["Hüftbeuger"],
    equipment: "Kein Equipment",
    difficulty: "Mittel",
    description: "Unterer Bauch — sehr effektiv und oft vernachlässigt.",
    steps: [
      "Rücken auf dem Boden oder an Klimmzugstange hängen.",
      "Beine gestreckt oder leicht gebeugt.",
      "Beine heben bis 90° (oder höher).",
      "Kontrolliert absenken ohne den Boden zu berühren.",
    ],
    tips: [
      "Lendenbereich am Boden lassen.",
      "Langsam = mehr Aktivierung.",
    ],
    calories_per_minute: 5,
  },
  // KARDIO
  {
    id: "running",
    name: "Laufen",
    muscle_group: "Kardio",
    secondary_muscles: ["Beine", "Core"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Die einfachste und effektivste Kardio-Methode.",
    steps: [
      "Aufrechte Körperhaltung, Blick nach vorne.",
      "Arme im 90° Winkel schwingen.",
      "Mittelfuß zuerst aufsetzen.",
      "Gleichmäßiger Atemrhythmus.",
    ],
    tips: [
      "Langsam starten, Ausdauer steigern.",
      "2 Min gehen, 1 Min laufen für Einsteiger.",
    ],
    calories_per_minute: 10,
  },
  {
    id: "hiit",
    name: "HIIT Training",
    muscle_group: "Kardio",
    secondary_muscles: ["Ganzkörper"],
    equipment: "Kein Equipment",
    difficulty: "Fortgeschritten",
    description: "Hochintensives Intervalltraining — maximale Fettverbrennung in kurzer Zeit.",
    steps: [
      "20 Sek maximale Intensität (z.B. Burpees, Sprints).",
      "10 Sek Pause.",
      "8 Runden = 4 Minuten (Tabata).",
      "Beliebig erweitern.",
    ],
    tips: [
      "Wirklich maximale Intensität in den Arbeitsintervallen.",
      "Nur 2–3× pro Woche.",
    ],
    calories_per_minute: 14,
  },
  {
    id: "cycling",
    name: "Fahrrad / Ergometer",
    muscle_group: "Kardio",
    secondary_muscles: ["Beine"],
    equipment: "Fahrrad",
    difficulty: "Anfänger",
    description: "Gelenkschonende Ausdauer — ideal für Einsteiger und Regeneration.",
    steps: [
      "Sattelhöhe so einstellen dass Knie leicht gebeugt bei voller Ausdehnung.",
      "Gleichmäßiges Treten, nicht im Wiegeschritt.",
      "Widerstand langsam erhöhen.",
    ],
    tips: [
      "Ideal zum Aufwärmen oder aktiver Erholung.",
      "Puls zwischen 120–150 für Fettverbrennung.",
    ],
    calories_per_minute: 8,
  },
];

export const MUSCLE_GROUPS = [
  { name: "Brust", icon: "⬡", color: "#E24B4A" },
  { name: "Rücken", icon: "◈", color: "#378ADD" },
  { name: "Schultern", icon: "◎", color: "#EF9F27" },
  { name: "Bizeps", icon: "◇", color: "#1D9E75" },
  { name: "Trizeps", icon: "△", color: "#1D9E75" },
  { name: "Beine", icon: "◐", color: "#7F77DD" },
  { name: "Gesäß", icon: "●", color: "#D4537E" },
  { name: "Core", icon: "◉", color: "#BA7517" },
  { name: "Kardio", icon: "♡", color: "#5DCAA5" },
];
