export interface Exercise {
  id: string;
  name: string;
  muscle_group: string;
  secondary_muscles: string[];
  equipment: string;
  difficulty: "Anfänger" | "Mittel" | "Fortgeschritten";
  description: string;
  steps: string[];
  tips: string[];
  calories_per_minute: number;
}

export const EXERCISES: Exercise[] = [
  // BRUST
  {
    id: "bench-press",
    name: "Bankdrücken",
    muscle_group: "Brust",
    secondary_muscles: ["Trizeps", "Schultern"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Die Königsübung für die Brust — maximaler Muskelaufbau mit freiem Gewicht.",
    steps: [
      "Lege dich flach auf die Bank, Augen unter der Stange.",
      "Füße flach auf dem Boden, Rücken leicht gewölbt.",
      "Griffbreite etwas breiter als Schulterbreite.",
      "Stange abnehmen, senkrecht über der Brust halten.",
      "Kontrolliert absenken bis die Stange die Brust berührt.",
      "Explosiv nach oben drücken bis Arme fast gestreckt.",
    ],
    tips: [
      "Daumen immer um die Stange (kein falscher Griff).",
      "Ellenbogen nicht komplett verriegeln oben.",
      "Schulterblätter zusammenziehen und zur Bank drücken.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "push-up",
    name: "Liegestütz",
    muscle_group: "Brust",
    secondary_muscles: ["Trizeps", "Schultern", "Core"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Die beste Körpergewichtsübung für die Brust — überall und ohne Equipment.",
    steps: [
      "Hände schulterbreit auf dem Boden, Finger zeigen leicht nach außen.",
      "Körper bildet eine gerade Linie von Kopf bis Ferse.",
      "Core anspannen, Hüfte nicht hängen lassen.",
      "Absenken bis Brust fast den Boden berührt.",
      "Explosiv hochdrücken.",
    ],
    tips: [
      "Ellenbogen 45° zum Körper halten — nicht ausflaren.",
      "Knie-Variante für Anfänger erlaubt.",
      "Hände breiter = mehr Brustanteil.",
    ],
    calories_per_minute: 7,
  },
  {
    id: "cable-fly",
    name: "Kabelfliegende",
    muscle_group: "Brust",
    secondary_muscles: ["Schultern"],
    equipment: "Kabelzug",
    difficulty: "Mittel",
    description: "Isolationsübung für maximale Dehnung und Kontraktion der Brustmuskeln.",
    steps: [
      "Kabel auf Schulterhöhe einstellen, in die Mitte stellen.",
      "Einen Schritt nach vorne treten, Griffe in beide Hände.",
      "Leicht gebeugte Arme, Rumpf angespannt.",
      "Arme vor der Brust zusammenführen.",
      "Kontrolliert zurück in die Ausgangsposition.",
    ],
    tips: [
      "Leichte Beugung im Ellenbogen halten.",
      "Am Ende kurz einhalten und Brust anspannen.",
    ],
    calories_per_minute: 6,
  },
  {
    id: "dips-chest",
    name: "Dips (Brust)",
    muscle_group: "Brust",
    secondary_muscles: ["Trizeps", "Schultern"],
    equipment: "Dip-Stangen",
    difficulty: "Mittel",
    description: "Compound-Übung mit dem Körpergewicht — Fokus auf untere Brust.",
    steps: [
      "Auf Dip-Stangen hochdrücken, Arme gestreckt.",
      "Körper leicht nach vorne neigen (mehr Brust).",
      "Kontrolliert absenken bis Ellenbogen 90° gebeugt.",
      "Hochdrücken, kurz einhalten.",
    ],
    tips: [
      "Je mehr Vorneigung, desto mehr Brust.",
      "Für Anfänger: Band zur Unterstützung nutzen.",
    ],
    calories_per_minute: 9,
  },
  // RÜCKEN
  {
    id: "pull-up",
    name: "Klimmzug",
    muscle_group: "Rücken",
    secondary_muscles: ["Bizeps", "Schultern"],
    equipment: "Klimmzugstange",
    difficulty: "Mittel",
    description: "Die beste Rückenübung mit dem eigenen Körpergewicht.",
    steps: [
      "Stange im Obergriff (Hände zeigen weg), schulterbreit.",
      "Hängen mit gestreckten Armen.",
      "Schulterblätter zusammenziehen, dann hochziehen.",
      "Kinn über die Stange bringen.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Mit Schulterblättern starten, nicht mit den Armen.",
      "Körper leicht nach hinten neigen.",
      "Band für Assistenz nutzen wenn nötig.",
    ],
    calories_per_minute: 10,
  },
  {
    id: "deadlift",
    name: "Kreuzheben",
    muscle_group: "Rücken",
    secondary_muscles: ["Gesäß", "Hamstrings", "Core", "Trapez"],
    equipment: "Langhantel",
    difficulty: "Fortgeschritten",
    description: "Die mächtigste Grundübung — trainiert fast alle Muskelgruppen gleichzeitig.",
    steps: [
      "Stange über den Mittelfuß, Füße hüftbreit.",
      "Hüfte schieben, Stange greifen schulterbreit.",
      "Brust raus, Rücken gerade, Core anspannen.",
      "Stange nah am Körper halten, gleichzeitig Beine strecken und Hüfte nach vorne.",
      "Oben: Hüfte durchstrecken, Schultern zurück.",
      "Stange kontrolliert absenken.",
    ],
    tips: [
      "Rücken immer gerade — niemals runden!",
      "Mit leichtem Gewicht beginnen und Technik üben.",
      "Stange während der ganzen Bewegung am Körper halten.",
    ],
    calories_per_minute: 12,
  },
  {
    id: "lat-pulldown",
    name: "Latzug",
    muscle_group: "Rücken",
    secondary_muscles: ["Bizeps"],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Einsteigerfreundliche Alternative zum Klimmzug — Gewicht frei wählbar.",
    steps: [
      "Auf dem Latzug-Gerät Platz nehmen, Oberschenkel fixieren.",
      "Stange im breiten Obergriff fassen.",
      "Oberkörper leicht zurücklehnen.",
      "Stange zur Brust ziehen, Ellenbogen nach unten.",
      "Kontrolliert wieder strecken.",
    ],
    tips: [
      "Schulterblätter beim Ziehen zusammenführen.",
      "Nicht mit Schwung ziehen.",
    ],
    calories_per_minute: 7,
  },
  {
    id: "rowing",
    name: "Rudern mit Langhantel",
    muscle_group: "Rücken",
    secondary_muscles: ["Bizeps", "Core"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Horizontale Zugbewegung für mittleren und oberen Rücken.",
    steps: [
      "Hüftbreiter Stand, Langhantel aufheben.",
      "Rumpf nach vorne neigen (ca. 45°), Rücken gerade.",
      "Stange zum Bauchnabel ziehen, Ellenbogen nach hinten.",
      "Schulterblätter zusammendrücken.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Nicht mit dem Rücken schwingen.",
      "Stange bleibt nah am Körper.",
    ],
    calories_per_minute: 9,
  },
  // SCHULTERN
  {
    id: "overhead-press",
    name: "Schulterdrücken",
    muscle_group: "Schultern",
    secondary_muscles: ["Trizeps", "Trapez"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Die Grundübung für volle Schultermuskeln.",
    steps: [
      "Stand oder Sitzen, Langhantel vor der Brust auf Schulterhöhe.",
      "Griff etwas breiter als Schultern.",
      "Stange gerade nach oben drücken.",
      "Oben kurz einhalten.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Core die ganze Zeit angespannt.",
      "Kopf leicht zurückneigen wenn Stange vorbeigeht.",
      "Nicht im Hohlkreuz stehen.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "lateral-raise",
    name: "Seitheben",
    muscle_group: "Schultern",
    secondary_muscles: [],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Isolationsübung für breite, runde Schultern.",
    steps: [
      "Kurzhanteln in beide Hände, Arme hängen neben dem Körper.",
      "Leichte Beugung im Ellenbogen.",
      "Arme seitlich auf Schulterhöhe heben.",
      "Kurz halten, kontrolliert absenken.",
    ],
    tips: [
      "Kleinfinger leicht höher als Daumen (wie ausschütten).",
      "Nicht mit Schwung arbeiten.",
      "Lieber leicht als zu schwer.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "face-pull",
    name: "Face Pulls",
    muscle_group: "Schultern",
    secondary_muscles: ["Trapez", "Rotatorenmanschette"],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Unverzichtbar für Schultergesundheit und hintere Schulter.",
    steps: [
      "Kabelzug auf Kopfhöhe, Seilgriff befestigen.",
      "Einen Schritt zurücktreten.",
      "Seil zum Gesicht ziehen, Ellenbogen nach außen oben.",
      "Kontrolliert zurück.",
    ],
    tips: [
      "Tägliche Übung für gesunde Schultern.",
      "Mehr Wiederholungen als schweres Gewicht.",
    ],
    calories_per_minute: 5,
  },
  // ARME
  {
    id: "bicep-curl",
    name: "Bizeps-Curl",
    muscle_group: "Bizeps",
    secondary_muscles: [],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Die klassische Arm-Übung — isoliert den Bizeps perfekt.",
    steps: [
      "Kurzhanteln in beide Hände, Oberarme am Körper.",
      "Langsam hochcurlen, Ellenbogen bleibt ruhig.",
      "Oben einhalten und Bizeps anspannen.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Ellenbogen nicht nach vorne schwingen.",
      "Volle Bewegungsamplitude nutzen.",
      "Abwechselnd oder gleichzeitig.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "tricep-pushdown",
    name: "Trizeps-Pushdown",
    muscle_group: "Trizeps",
    secondary_muscles: [],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Effektivste Isolation für alle drei Trizeps-Köpfe.",
    steps: [
      "Kabelzug auf Kopfhöhe, Seilgriff oder gerades Griffstück.",
      "Ellenbogen nah am Körper fixieren.",
      "Unterarme nach unten drücken bis Arme gestreckt.",
      "Kurz halten, kontrolliert zurück.",
    ],
    tips: [
      "Ellenbogen nie bewegen.",
      "Am tiefsten Punkt Trizeps maximal anspannen.",
    ],
    calories_per_minute: 5,
  },
  // BEINE
  {
    id: "squat",
    name: "Kniebeuge",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß", "Core", "Rücken"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Die Königin der Beinübungen — baut Masse und Kraft wie keine andere.",
    steps: [
      "Stange auf dem oberen Rücken (nicht Nacken).",
      "Füße schulterbreit, Zehen leicht nach außen.",
      "Tief einatmen, Core anspannen.",
      "Hüfte nach hinten und unten — wie auf Stuhl setzen.",
      "Knie in Zehenrichtung drücken.",
      "Mindestens parallel, Rücken gerade.",
      "Explosiv hochdrücken.",
    ],
    tips: [
      "Fersen immer am Boden.",
      "Knie nicht nach innen fallen lassen.",
      "Tiefer ist besser — volle Amplitude.",
    ],
    calories_per_minute: 11,
  },
  {
    id: "leg-press",
    name: "Beinpresse",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß"],
    equipment: "Maschine",
    difficulty: "Anfänger",
    description: "Rückenfreundliche Alternative zur Kniebeuge.",
    steps: [
      "Auf der Beinpresse Platz nehmen, Füße schulterbreit auf der Plattform.",
      "Sicherungen lösen.",
      "Knie kontrolliert zur Brust beugen.",
      "Nicht ganz strecken (Knie nicht einrasten).",
    ],
    tips: [
      "Füße höher = mehr Gesäß und Hamstrings.",
      "Füße tiefer = mehr Quadrizeps.",
    ],
    calories_per_minute: 9,
  },
  {
    id: "lunge",
    name: "Ausfallschritt",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß", "Core"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Unilaterale Beinübung für Balance, Stabilität und Muskelaufbau.",
    steps: [
      "Aufrechter Stand, Hände in der Hüfte oder Kurzhanteln.",
      "Großen Schritt nach vorne machen.",
      "Hinteres Knie fast zum Boden bringen.",
      "Vorderes Knie bleibt über dem Fuß.",
      "Abdrücken und zurück in Ausgangsposition.",
    ],
    tips: [
      "Rumpf gerade halten.",
      "Vorderes Knie nicht über die Zehen.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "romanian-deadlift",
    name: "Rumänisches Kreuzheben",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß", "Rücken"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Beste Übung für Hamstrings und Gesäß — maximale Dehnung.",
    steps: [
      "Langhantel vor dem Körper halten, Füße hüftbreit.",
      "Hüfte nach hinten schieben, Rücken gerade.",
      "Stange nah am Körper an den Beinen heruntergleiten lassen.",
      "Bis zur Dehnung im hinteren Oberschenkel.",
      "Hüfte nach vorne — zurück in Startposition.",
    ],
    tips: [
      "Knie leicht gebeugt.",
      "Dehnung spüren, nicht tiefer als nötig.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "calf-raise",
    name: "Wadenheben",
    muscle_group: "Beine",
    secondary_muscles: [],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Isoliert die Waden — oft unterschätzt aber wichtig.",
    steps: [
      "Auf einer Stufe oder dem Boden stehen.",
      "Fersen heben so hoch wie möglich.",
      "2 Sekunden oben halten.",
      "Tief absenken für maximale Dehnung.",
    ],
    tips: [
      "Langsame, kontrollierte Bewegung.",
      "Volle Amplitude — auch tief gehen.",
    ],
    calories_per_minute: 5,
  },
  // GESÄSS
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    muscle_group: "Gesäß",
    secondary_muscles: ["Hamstrings", "Core"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Die effektivste Übung für maximale Gesäß-Aktivierung.",
    steps: [
      "Oberer Rücken auf einer Bank, Langhantel auf den Hüften.",
      "Füße hüftbreit, Knie 90°.",
      "Hüfte nach oben drücken bis Körper gerade.",
      "Gesäß oben maximal anspannen.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Kinn zur Brust halten.",
      "Oben kurz pausieren und Gesäß pressen.",
      "Füße etwas weiter vorne = mehr Gluteus.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    muscle_group: "Gesäß",
    secondary_muscles: ["Hamstrings"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Einsteigerversion des Hip Thrust — überall ohne Equipment.",
    steps: [
      "Rücken auf dem Boden, Knie angewinkelt.",
      "Füße flach auf dem Boden, hüftbreit.",
      "Hüfte hochdrücken bis Schultern-Hüfte-Knie in einer Linie.",
      "Gesäß anspannen und 2 Sek halten.",
      "Absenken ohne abzulegen.",
    ],
    tips: [
      "Mit einbeiniger Variante steigern.",
      "Widerstandsband für mehr Intensität.",
    ],
    calories_per_minute: 5,
  },
  // CORE
  {
    id: "plank",
    name: "Planke",
    muscle_group: "Core",
    secondary_muscles: ["Schultern", "Gesäß"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Die effektivste isometrische Core-Übung.",
    steps: [
      "Unterarme auf dem Boden, Ellenbogen unter den Schultern.",
      "Körper bildet eine gerade Linie.",
      "Gesäß nicht heben oder senken.",
      "Tief atmen, Position halten.",
    ],
    tips: [
      "Bauch aktiv einziehen.",
      "Gesäß leicht anspannen.",
      "Zeit langsam steigern.",
    ],
    calories_per_minute: 4,
  },
  {
    id: "crunch",
    name: "Crunch",
    muscle_group: "Core",
    secondary_muscles: [],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Klassische Bauchübung für den oberen Bereich.",
    steps: [
      "Rücken auf dem Boden, Knie angewinkelt.",
      "Hände locker hinter dem Kopf (nicht ziehen).",
      "Oberkörper vom Boden abheben — nur bis Schulterblätter frei sind.",
      "Bauch anspannen, nicht mit Schwung.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Nacken entspannt lassen.",
      "Kleine Bewegung — aber bewusst.",
    ],
    calories_per_minute: 4,
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    muscle_group: "Core",
    secondary_muscles: ["Schräge Bauchmuskeln"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Rotationsbewegung für Schräge Bauchmuskeln.",
    steps: [
      "Sitzen, Oberkörper leicht zurückgelehnt.",
      "Füße vom Boden heben (oder auf dem Boden lassen).",
      "Hände zusammen, abwechselnd links und rechts rotieren.",
    ],
    tips: [
      "Medizinball oder Kurzhantel für mehr Intensität.",
      "Kontrolliert rotieren, nicht schwingen.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "leg-raise",
    name: "Beinheben",
    muscle_group: "Core",
    secondary_muscles: ["Hüftbeuger"],
    equipment: "Kein Equipment",
    difficulty: "Mittel",
    description: "Unterer Bauch — sehr effektiv und oft vernachlässigt.",
    steps: [
      "Rücken auf dem Boden oder an Klimmzugstange hängen.",
      "Beine gestreckt oder leicht gebeugt.",
      "Beine heben bis 90° (oder höher).",
      "Kontrolliert absenken ohne den Boden zu berühren.",
    ],
    tips: [
      "Lendenbereich am Boden lassen.",
      "Langsam = mehr Aktivierung.",
    ],
    calories_per_minute: 5,
  },
  // KARDIO
  {
    id: "running",
    name: "Laufen",
    muscle_group: "Kardio",
    secondary_muscles: ["Beine", "Core"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Die einfachste und effektivste Kardio-Methode.",
    steps: [
      "Aufrechte Körperhaltung, Blick nach vorne.",
      "Arme im 90° Winkel schwingen.",
      "Mittelfuß zuerst aufsetzen.",
      "Gleichmäßiger Atemrhythmus.",
    ],
    tips: [
      "Langsam starten, Ausdauer steigern.",
      "2 Min gehen, 1 Min laufen für Einsteiger.",
    ],
    calories_per_minute: 10,
  },
  {
    id: "hiit",
    name: "HIIT Training",
    muscle_group: "Kardio",
    secondary_muscles: ["Ganzkörper"],
    equipment: "Kein Equipment",
    difficulty: "Fortgeschritten",
    description: "Hochintensives Intervalltraining — maximale Fettverbrennung in kurzer Zeit.",
    steps: [
      "20 Sek maximale Intensität (z.B. Burpees, Sprints).",
      "10 Sek Pause.",
      "8 Runden = 4 Minuten (Tabata).",
      "Beliebig erweitern.",
    ],
    tips: [
      "Wirklich maximale Intensität in den Arbeitsintervallen.",
      "Nur 2–3× pro Woche.",
    ],
    calories_per_minute: 14,
  },
  {
    id: "cycling",
    name: "Fahrrad / Ergometer",
    muscle_group: "Kardio",
    secondary_muscles: ["Beine"],
    equipment: "Fahrrad",
    difficulty: "Anfänger",
    description: "Gelenkschonende Ausdauer — ideal für Einsteiger und Regeneration.",
    steps: [
      "Sattelhöhe so einstellen dass Knie leicht gebeugt bei voller Ausdehnung.",
      "Gleichmäßiges Treten, nicht im Wiegeschritt.",
      "Widerstand langsam erhöhen.",
    ],
    tips: [
      "Ideal zum Aufwärmen oder aktiver Erholung.",
      "Puls zwischen 120–150 für Fettverbrennung.",
    ],
    calories_per_minute: 8,
  },

  // ── BRUST (erweitert) ──────────────────────────────────────────
  {
    id: "incline-bench-press",
    name: "Schrägbankdrücken (Langhantel)",
    muscle_group: "Brust",
    secondary_muscles: ["Schultern", "Trizeps"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Fokus auf die obere Brust — für volle, runde Brustmuskeln unersetzlich.",
    steps: [
      "Bank auf 30–45° einstellen.",
      "Griffbreite etwas breiter als Schultern.",
      "Stange zur oberen Brust absenken.",
      "Explosiv nach oben drücken.",
    ],
    tips: [
      "Je steiler die Bank, desto mehr Schulteranteil.",
      "30–45° ist optimal für die obere Brust.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "incline-dumbbell-press",
    name: "Schrägbankdrücken (Kurzhanteln)",
    muscle_group: "Brust",
    secondary_muscles: ["Schultern", "Trizeps"],
    equipment: "Kurzhanteln",
    difficulty: "Mittel",
    description: "Mehr Bewegungsfreiheit als mit Langhantel — größere Dehnung.",
    steps: [
      "Bank auf 30–45° einstellen, Kurzhanteln in beide Hände.",
      "Hanteln auf Brustbreite halten, Ellenbogen 70° zum Körper.",
      "Kontrolliert absenken bis zur maximalen Dehnung.",
      "Hochdrücken, oben leicht zusammenführen.",
    ],
    tips: [
      "Am Ende der Bewegung Hanteln leicht zusammendrehen für mehr Kontraktion.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "dumbbell-fly",
    name: "Fliegende (Kurzhanteln)",
    muscle_group: "Brust",
    secondary_muscles: ["Schultern"],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Isolationsübung für maximale Dehnung und Weite der Brust.",
    steps: [
      "Flach auf der Bank liegen, Kurzhanteln über der Brust.",
      "Arme leicht gebeugt, Ellenbogen weich.",
      "Arme seitlich absenken — weiter Bogen wie Umarmen.",
      "Zurück zur Startposition durch die Brust zusammendrücken.",
    ],
    tips: [
      "Leichte Beugung im Ellenbogen immer beibehalten.",
      "Keine Pressübung — keine gerade Linie, sondern Bogen.",
    ],
    calories_per_minute: 6,
  },
  {
    id: "machine-chest-press",
    name: "Brustpresse (Maschine)",
    muscle_group: "Brust",
    secondary_muscles: ["Trizeps", "Schultern"],
    equipment: "Maschine",
    difficulty: "Anfänger",
    description: "Einsteigervariante mit geführter Bewegung — ideal zum Lernen.",
    steps: [
      "Sitzposition anpassen: Griffe auf Brusthöhe.",
      "Rücken an die Lehne drücken.",
      "Griffe nach vorne drücken bis Arme fast gestreckt.",
      "Kontrolliert zurück.",
    ],
    tips: [
      "Rücken nicht von der Lehne lösen.",
      "Schulterblätter zusammenziehen.",
    ],
    calories_per_minute: 7,
  },
  {
    id: "decline-bench-press",
    name: "Negatives Bankdrücken",
    muscle_group: "Brust",
    secondary_muscles: ["Trizeps"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Untere Brust & Übergang zu den Rippenbogen — komplette Brust-Entwicklung.",
    steps: [
      "Bank auf −15° bis −30° einstellen.",
      "Beine unter die Polster klemmen.",
      "Griffbreite schulterbreit bis etwas breiter.",
      "Stange zur unteren Brust absenken und hochdrücken.",
    ],
    tips: [
      "Vorsicht: nicht zu steil, sonst Blutandrang zum Kopf.",
    ],
    calories_per_minute: 8,
  },

  // ── RÜCKEN (erweitert) ─────────────────────────────────────────
  {
    id: "t-bar-row",
    name: "T-Bar Rudern",
    muscle_group: "Rücken",
    secondary_muscles: ["Bizeps", "Core"],
    equipment: "Maschine",
    difficulty: "Mittel",
    description: "Schweres Volumentraining für mittleren und unteren Rücken.",
    steps: [
      "Auf dem T-Bar-Gerät Platz nehmen, Brustpolster einstellen.",
      "Griffe fassen, Rücken gerade.",
      "Stange zum Bauch ziehen, Ellenbogen nah am Körper.",
      "Schulterblätter zusammendrücken.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Enger Griff = mehr Rücken, breiter Griff = mehr Schultern.",
    ],
    calories_per_minute: 9,
  },
  {
    id: "single-arm-db-row",
    name: "Einarmiges KH-Rudern",
    muscle_group: "Rücken",
    secondary_muscles: ["Bizeps"],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Beste unilaterale Rückenübung — volle Bewegungsamplitude.",
    steps: [
      "Knie und Hand auf der Bank abstützen.",
      "Kurzhantel mit der freien Hand hängen lassen.",
      "Hantel zur Hüfte ziehen, Ellenbogen nach hinten oben.",
      "Schulterblatt zusammenziehen, kontrolliert absenken.",
    ],
    tips: [
      "Rumpf parallel zum Boden halten.",
      "Schulter am Ende der Bewegung anheben für mehr Range.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "seated-cable-row",
    name: "Kabelrudern (sitzend)",
    muscle_group: "Rücken",
    secondary_muscles: ["Bizeps", "Core"],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Konstantzug durch den ganzen Bewegungsablauf — ideal für Muskelaufbau.",
    steps: [
      "Sitzend am Kabelzug, Füße auf den Stützen.",
      "Griff mit beiden Händen, Oberkörper leicht nach vorne.",
      "Griff zum Bauch ziehen, dabei aufrichten.",
      "Schulterblätter zusammenpressen.",
      "Kontrolliert zurück — leicht vorneigen.",
    ],
    tips: [
      "Nicht zu weit nach vorne lehnen.",
      "Rücken die ganze Zeit gerade.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "hyperextension",
    name: "Rückenstrecker (Hyperextension)",
    muscle_group: "Rücken",
    secondary_muscles: ["Gesäß", "Hamstrings"],
    equipment: "Maschine",
    difficulty: "Anfänger",
    description: "Isoliert den unteren Rücken und schützt vor Verletzungen.",
    steps: [
      "Auf dem Hyperextensions-Gerät die Fersen einklemmen.",
      "Oberkörper nach unten hängen lassen.",
      "Rücken gerade aufrichten bis Körper gerade ist.",
      "Kurz oben halten, kontrolliert absenken.",
    ],
    tips: [
      "Nicht überstrecken — Körper geradelegen reicht.",
      "Gewicht auf der Brust für mehr Intensität.",
    ],
    calories_per_minute: 6,
  },
  {
    id: "shrug",
    name: "Nackenziehen / Shrug",
    muscle_group: "Rücken",
    secondary_muscles: ["Trapez"],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Isoliert den Trapezmuskel für einen starken Nacken.",
    steps: [
      "Kurzhanteln oder Langhantel in den Händen, Arme gerade.",
      "Schultern so hoch wie möglich hochziehen.",
      "2 Sekunden oben halten.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Keine Kreisbewegung — nur hoch und runter.",
      "Schweres Gewicht für mehr Wachstum.",
    ],
    calories_per_minute: 6,
  },
  {
    id: "good-morning",
    name: "Good Morning",
    muscle_group: "Rücken",
    secondary_muscles: ["Hamstrings", "Gesäß"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Stärkt den unteren Rücken und die Hinterkette — wichtig für Kreuzheben.",
    steps: [
      "Stange auf dem oberen Rücken wie beim Kniebeugen.",
      "Knie leicht gebeugt, Füße hüftbreit.",
      "Oberkörper nach vorne neigen bis fast parallel zum Boden.",
      "Durch Hüftstreckung wieder aufrichten.",
    ],
    tips: [
      "Rücken immer gerade — niemals runden.",
      "Leichtes Gewicht zum Einstieg.",
    ],
    calories_per_minute: 8,
  },

  // ── SCHULTERN (erweitert) ──────────────────────────────────────
  {
    id: "arnold-press",
    name: "Arnold Press",
    muscle_group: "Schultern",
    secondary_muscles: ["Trizeps"],
    equipment: "Kurzhanteln",
    difficulty: "Mittel",
    description: "Alle drei Schulterköpfe in einer Bewegung — Arnie's Lieblingsübung.",
    steps: [
      "Sitzen, Kurzhanteln vor dem Gesicht, Handflächen zu dir.",
      "Beim Hochdrücken die Hände nach außen drehen.",
      "Oben: Handflächen zeigen nach vorne.",
      "Beim Absenken zurückdrehen.",
    ],
    tips: [
      "Langsame Rotation für maximalen Muskelkontakt.",
      "Mittleres Gewicht, saubere Technik.",
    ],
    calories_per_minute: 7,
  },
  {
    id: "upright-row",
    name: "Vorgebeugtes Seitheben",
    muscle_group: "Schultern",
    secondary_muscles: ["Trapez"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Mittlere und hintere Schulter plus Trapez — einen breiten Rücken formen.",
    steps: [
      "Langhantel im Untergriff schulterbreit greifen.",
      "Stange nah am Körper nach oben ziehen.",
      "Ellenbogen führen die Bewegung — höher als die Stange.",
      "Bis Kinnhöhe, dann kontrolliert absenken.",
    ],
    tips: [
      "Nicht zu schwer — Schultergelenk schonen.",
      "Ellenbogen zeigen immer nach außen oben.",
    ],
    calories_per_minute: 7,
  },
  {
    id: "rear-delt-fly",
    name: "Hintere Schulter Fliegende",
    muscle_group: "Schultern",
    secondary_muscles: ["Rücken", "Trapez"],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Hintere Schulter — oft vernachlässigt, aber für Schultergesundheit entscheidend.",
    steps: [
      "Vorgebeugt stehen oder auf Bank sitzen.",
      "Kurzhanteln hängen lassen.",
      "Arme mit leichter Beugung seitlich hochführen.",
      "Schulterblätter zusammenziehen oben.",
    ],
    tips: [
      "Sehr leichtes Gewicht — hintere Schulter ist schwach.",
      "Daumen leicht nach unten drehen für mehr Aktivierung.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "front-raise",
    name: "Frontheben",
    muscle_group: "Schultern",
    secondary_muscles: [],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Vordere Schulter — ideal als Ergänzung zu Druckübungen.",
    steps: [
      "Kurzhanteln vor dem Körper, Handflächen nach unten.",
      "Arme gestreckt oder leicht gebeugt.",
      "Alternierend oder gleichzeitig auf Schulterhöhe heben.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Nicht schwingen.",
      "Vordere Schulter wird durch Druckübungen mittrainiert — leicht halten.",
    ],
    calories_per_minute: 5,
  },

  // ── BIZEPS (erweitert) ─────────────────────────────────────────
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    muscle_group: "Bizeps",
    secondary_muscles: ["Unterarme"],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Brachialis und Unterarme — für dicke, volle Arme.",
    steps: [
      "Kurzhanteln seitlich, Daumen zeigen nach oben (neutraler Griff).",
      "Oberarme ruhig am Körper.",
      "Curlen ohne Rotation der Handgelenke.",
    ],
    tips: [
      "Neutraler Griff die ganze Zeit behalten.",
      "Wechselseitig oder gleichzeitig.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    muscle_group: "Bizeps",
    secondary_muscles: [],
    equipment: "Maschine",
    difficulty: "Anfänger",
    description: "Fixierter Oberarm — maximale Isolation ohne Schummeln.",
    steps: [
      "Arm auf der Schrägstütze ablegen.",
      "EZ-Bar oder Kurzhantel langsam absenken.",
      "Vollständig strecken, dann hochcurlen.",
      "Oben Bizeps maximal anspannen.",
    ],
    tips: [
      "Keine Hilfe durch den anderen Arm.",
      "Letzte 5° der Streckung sind für maximale Dehnung wichtig.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "cable-curl",
    name: "Kabel-Curl",
    muscle_group: "Bizeps",
    secondary_muscles: [],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Konstantzug durch die ganze Bewegung — optimale Zeit unter Spannung.",
    steps: [
      "Kabelzug unten, gerades Griffstück oder EZ-Bar.",
      "Oberarme ruhig, curlen bis Unterarme vertikal.",
      "Kurz oben halten.",
      "Kontrolliert absenken — Kabel bleibt unter Spannung.",
    ],
    tips: [
      "Ideal am Ende des Bizepsworkouts für den Pump.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "ez-bar-curl",
    name: "EZ-Bar Curl",
    muscle_group: "Bizeps",
    secondary_muscles: ["Unterarme"],
    equipment: "Langhantel",
    difficulty: "Anfänger",
    description: "Handgelenksschonende Alternative zur geraden Stange.",
    steps: [
      "EZ-Bar im Untergriff, Hände schulterbreit.",
      "Oberarme ruhig am Körper.",
      "Stange hochcurlen bis Unterarme vertikal.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "EZ-Bar reduziert Handgelenksstress vs. gerade Stange.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "concentration-curl",
    name: "Konzentrationscurl",
    muscle_group: "Bizeps",
    secondary_muscles: [],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Maximale Isolation und Peakkontraktion des Bizeps.",
    steps: [
      "Sitzen, Ellenbogen auf dem Oberschenkel abstützen.",
      "Kurzhantel langsam hochcurlen.",
      "Oben maximal anspannen und halten.",
      "Langsam absenken.",
    ],
    tips: [
      "Kein Schwung — reiner Bizepseinsatz.",
    ],
    calories_per_minute: 4,
  },

  // ── TRIZEPS (erweitert) ────────────────────────────────────────
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    muscle_group: "Trizeps",
    secondary_muscles: [],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Schwere Isolationsübung für alle drei Trizepsköpfe.",
    steps: [
      "Flach auf der Bank liegen, EZ-Bar oder Langhantel über der Brust.",
      "Ellenbogen zeigen nach oben, nicht nach außen.",
      "Stange zur Stirn/hinter den Kopf absenken.",
      "Trizeps streckt die Arme zurück.",
    ],
    tips: [
      "Ellenbogen nicht ausflaren.",
      "Kontrollierte Bewegung — Verletzungsgefahr bei zu schnell.",
    ],
    calories_per_minute: 6,
  },
  {
    id: "close-grip-bench",
    name: "Enges Bankdrücken",
    muscle_group: "Trizeps",
    secondary_muscles: ["Brust", "Schultern"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Compound-Trizepsübung mit schwerem Gewicht möglich.",
    steps: [
      "Langhantel schulterbreit oder enger greifen.",
      "Ellenbogen nah am Körper halten.",
      "Stange zur unteren Brust absenken.",
      "Durch Trizeps hochdrücken.",
    ],
    tips: [
      "Ellenbogen zeigen nach hinten, nicht seitlich.",
      "Zu enger Griff belastet die Handgelenke.",
    ],
    calories_per_minute: 8,
  },
  {
    id: "overhead-tricep-extension",
    name: "Trizeps-Überkopfdrücken",
    muscle_group: "Trizeps",
    secondary_muscles: [],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Langer Trizepskopf — maximale Dehnung über dem Kopf.",
    steps: [
      "Stehen oder sitzen, eine Kurzhantel mit beiden Händen über dem Kopf.",
      "Ellenbogen zeigen nach vorne.",
      "Hantel hinter den Kopf absenken.",
      "Durch Trizeps nach oben strecken.",
    ],
    tips: [
      "Ellenbogen so wenig wie möglich bewegen.",
      "Trizeps-Überkopf gibt maximale Dehnung des langen Kopfes.",
    ],
    calories_per_minute: 6,
  },
  {
    id: "dips-tricep",
    name: "Dips (Trizeps)",
    muscle_group: "Trizeps",
    secondary_muscles: ["Brust", "Schultern"],
    equipment: "Dip-Stangen",
    difficulty: "Mittel",
    description: "Effektivster Trizeps-Compound — schweres Körpergewicht möglich.",
    steps: [
      "Auf Dip-Stangen hochdrücken.",
      "Oberkörper aufrecht halten (mehr Trizeps).",
      "Kontrolliert absenken bis Ellenbogen 90°.",
      "Hochdrücken.",
    ],
    tips: [
      "Aufrechter Körper = mehr Trizeps, vorgebeugt = mehr Brust.",
      "Zusatzgewicht möglich mit Gürtel.",
    ],
    calories_per_minute: 9,
  },

  // ── BEINE (erweitert) ──────────────────────────────────────────
  {
    id: "bulgarian-split-squat",
    name: "Bulgarische Kniebeuge",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß", "Core"],
    equipment: "Kurzhanteln",
    difficulty: "Mittel",
    description: "Härteste Beinübung — baut unilateral Kraft und Masse auf.",
    steps: [
      "Hinteres Bein auf einer Bank, vorderes Bein weit vorne.",
      "Kurzhanteln in den Händen oder KH auf den Schultern.",
      "Hinteres Knie fast zum Boden absenken.",
      "Durch das vordere Bein hochdrücken.",
    ],
    tips: [
      "Je weiter vorne der Fuß, desto mehr Gesäß.",
      "Balance ist anfangs schwierig — leicht beginnen.",
    ],
    calories_per_minute: 10,
  },
  {
    id: "hack-squat",
    name: "Hack Squat (Maschine)",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß"],
    equipment: "Maschine",
    difficulty: "Mittel",
    description: "Führt durch tiefe Kniebeuge mit Rückenunterstützung.",
    steps: [
      "Schultern unter die Polster schieben, Füße auf der Plattform.",
      "Sicherungen lösen.",
      "Tief einbeugen bis Oberschenkel parallel oder tiefer.",
      "Hochdrücken — Knie nicht einrasten.",
    ],
    tips: [
      "Füße hoch auf der Plattform = mehr Gesäß.",
      "Tief gehen für maximale Quadrizeps-Aktivierung.",
    ],
    calories_per_minute: 10,
  },
  {
    id: "leg-extension",
    name: "Beinstrecker",
    muscle_group: "Beine",
    secondary_muscles: [],
    equipment: "Maschine",
    difficulty: "Anfänger",
    description: "Isoliert den Quadrizeps — perfekt zum Aufwärmen oder Finisher.",
    steps: [
      "Auf dem Beinstrecker-Gerät sitzen, Rücken an die Lehne.",
      "Polster auf Fußhöhe einstellen.",
      "Beine strecken bis fast komplett ausgestreckt.",
      "Quadrizeps anspannen, kontrolliert absenken.",
    ],
    tips: [
      "Nicht mit Schwung arbeiten.",
      "Am Ende kurz halten für maximale Kontraktion.",
    ],
    calories_per_minute: 6,
  },
  {
    id: "leg-curl",
    name: "Beinbeuger",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß"],
    equipment: "Maschine",
    difficulty: "Anfänger",
    description: "Isoliert die Hamstrings — wichtig für Balance mit Quadrizeps.",
    steps: [
      "Auf dem Leg-Curl-Gerät liegen oder sitzen.",
      "Polster auf Fußhöhe einstellen.",
      "Fersen zur Gesäß ziehen.",
      "Oben halten, kontrolliert strecken.",
    ],
    tips: [
      "Hüfte auf der Unterlage lassen.",
      "Fußspitzen leicht anziehen für mehr Hamstring-Aktivierung.",
    ],
    calories_per_minute: 6,
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    muscle_group: "Beine",
    secondary_muscles: ["Core", "Gesäß"],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Einsteigerfreundliche Kniebeuge — perfekte Technik lernen.",
    steps: [
      "Kurzhantel vertikal vor der Brust mit beiden Händen halten.",
      "Füße etwas breiter als Schulterbreite, Zehen leicht nach außen.",
      "Tief einbeugen — Ellenbogen innen an den Knien.",
      "Hochdrücken.",
    ],
    tips: [
      "Kurzhantel zieht das Gewicht nach vorne — hilft beim aufrechten Oberkörper.",
      "Ideal zum Technik lernen.",
    ],
    calories_per_minute: 9,
  },
  {
    id: "sumo-squat",
    name: "Sumo Kniebeuge",
    muscle_group: "Beine",
    secondary_muscles: ["Gesäß", "Innenschenkel"],
    equipment: "Kurzhanteln",
    difficulty: "Anfänger",
    description: "Breite Fußposition aktiviert Innenschenkel und Gesäß stärker.",
    steps: [
      "Sehr breite Fußstellung, Zehen stark nach außen.",
      "Kurzhantel zwischen den Beinen hängen lassen.",
      "Tief einbeugen — Knie in Zehenrichtung.",
      "Hochdrücken.",
    ],
    tips: [
      "Rücken gerade halten.",
      "Je breiter, desto mehr Innenschenkel.",
    ],
    calories_per_minute: 9,
  },
  {
    id: "front-squat",
    name: "Frontkniebeuge",
    muscle_group: "Beine",
    secondary_muscles: ["Core", "Schultern"],
    equipment: "Langhantel",
    difficulty: "Fortgeschritten",
    description: "Betont den Quadrizeps noch stärker als normale Kniebeuge.",
    steps: [
      "Stange vor den Schultern auf den Fingerspitzen ablegen.",
      "Ellenbogen so hoch wie möglich.",
      "Sehr aufrechter Oberkörper.",
      "Tief einbeugen, Knie nach vorne.",
      "Explosiv hochdrücken.",
    ],
    tips: [
      "Mobilität in Handgelenken und Schultern nötig.",
      "Viel Mobility-Übungen am Anfang.",
    ],
    calories_per_minute: 11,
  },

  // ── GESÄSS (erweitert) ─────────────────────────────────────────
  {
    id: "cable-kickback",
    name: "Kabel-Kickback",
    muscle_group: "Gesäß",
    secondary_muscles: ["Hamstrings"],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Isoliert den Gluteus Maximus — ideal für Form und Aktivierung.",
    steps: [
      "Kabelzug unten, Fußmanschette anlegen.",
      "Leicht nach vorne beugen.",
      "Bein nach hinten-oben strecken.",
      "Gesäß oben maximal anspannen.",
      "Kontrolliert zurück.",
    ],
    tips: [
      "Hüfte nicht drehen.",
      "Langsame Bewegung für mehr Muskelgefühl.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "abductor-machine",
    name: "Abduktor (Maschine)",
    muscle_group: "Gesäß",
    secondary_muscles: ["Hüftabduktoren"],
    equipment: "Maschine",
    difficulty: "Anfänger",
    description: "Seitliche Gesäßmuskeln — breites, rundes Gesäß formen.",
    steps: [
      "Auf der Abduktionsmaschine sitzen.",
      "Knie gegen die Polster, Oberschenkel zusammen starten.",
      "Beine auseinander drücken.",
      "Kurz halten, kontrolliert zurück.",
    ],
    tips: [
      "Langsame Bewegung für besseren Muskelkontakt.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "step-up",
    name: "Step-Up",
    muscle_group: "Gesäß",
    secondary_muscles: ["Beine", "Core"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Funktionelle Übung für Gesäß und Beine — überall machbar.",
    steps: [
      "Vor einer Box oder Stufe stehen.",
      "Einen Fuß auf die Box setzen.",
      "Durch die Ferse des oben stehenden Beins hochdrücken.",
      "Anderes Bein nachziehen.",
      "Wechseln.",
    ],
    tips: [
      "Je höher die Box, desto mehr Gesäß.",
      "Gewicht für mehr Intensität.",
    ],
    calories_per_minute: 7,
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Kreuzheben",
    muscle_group: "Gesäß",
    secondary_muscles: ["Beine", "Rücken", "Innenschenkel"],
    equipment: "Langhantel",
    difficulty: "Mittel",
    description: "Breitbeinige Variante betont Gesäß und Innenschenkel.",
    steps: [
      "Breite Fußstellung, Zehen stark nach außen.",
      "Hände schulterbreit greifen — eng zwischen den Beinen.",
      "Rücken gerade, Hüfte tief.",
      "Gleichzeitig Beine strecken und Hüfte nach vorne.",
      "Kontrolliert absenken.",
    ],
    tips: [
      "Knie immer in Zehenrichtung halten.",
      "Rücken immer gerade.",
    ],
    calories_per_minute: 10,
  },
  {
    id: "donkey-kick",
    name: "Donkey Kick",
    muscle_group: "Gesäß",
    secondary_muscles: ["Hamstrings"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Aktivierungsübung und Isolationsübung — überall ohne Geräte.",
    steps: [
      "Auf Händen und Knien (Vierfüßerstand).",
      "Ein Bein nach hinten oben strecken.",
      "Ferse zur Decke, Gesäß anspannen.",
      "Kontrolliert zurück ohne abzusetzen.",
    ],
    tips: [
      "Hüfte nicht verdrehen.",
      "Mit Widerstandsband für mehr Intensität.",
    ],
    calories_per_minute: 5,
  },

  // ── CORE (erweitert) ───────────────────────────────────────────
  {
    id: "ab-wheel",
    name: "Ab Wheel Rollout",
    muscle_group: "Core",
    secondary_muscles: ["Schultern", "Rücken"],
    equipment: "Kein Equipment",
    difficulty: "Fortgeschritten",
    description: "Eine der härtesten Core-Übungen — komplette Stabilität nötig.",
    steps: [
      "Kniend mit dem Ab Wheel vor sich.",
      "Rad langsam nach vorne rollen — Körper fast parallel zum Boden.",
      "Core maximal anspannen.",
      "Zurückrollen durch Bauch und Hüftbeuger.",
    ],
    tips: [
      "Rücken nicht durchhängen lassen.",
      "Starte mit halber Amplitude.",
    ],
    calories_per_minute: 7,
  },
  {
    id: "cable-crunch",
    name: "Kabel-Crunch",
    muscle_group: "Core",
    secondary_muscles: [],
    equipment: "Kabelzug",
    difficulty: "Anfänger",
    description: "Gewichteter Crunch mit konstantem Zug — beste Bauchabdominalisierung.",
    steps: [
      "Kabelzug oben, Seilgriff fassen.",
      "Kniend vor dem Gerät.",
      "Ellenbogen zu den Knien nach unten ziehen.",
      "Bauch rund machen — nicht Hüfte beugen.",
    ],
    tips: [
      "Bewegung kommt aus dem Bauch, nicht aus der Hüfte.",
    ],
    calories_per_minute: 5,
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    muscle_group: "Core",
    secondary_muscles: ["Schultern", "Kardio"],
    equipment: "Kein Equipment",
    difficulty: "Mittel",
    description: "Core-Stabilität mit Kardio-Effekt — kalorienreich und effektiv.",
    steps: [
      "Liegestütz-Position, Arme gestreckt.",
      "Abwechselnd Knie zur Brust ziehen.",
      "So schnell wie möglich, aber kontrolliert.",
    ],
    tips: [
      "Hüfte nicht hochheben.",
      "Gleichmäßiges Tempo für mehr Ausdauer.",
    ],
    calories_per_minute: 10,
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    muscle_group: "Core",
    secondary_muscles: ["Hüftbeuger"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Aktiviert tief liegende Bauchmuskulatur — perfekt für Rückengesundheit.",
    steps: [
      "Rücken auf dem Boden, Arme senkrecht zur Decke.",
      "Beine angewinkelt in der Luft, 90°.",
      "Arm und gegenüberliegendes Bein gleichzeitig strecken.",
      "Lendenwirbel am Boden halten.",
      "Zurück zur Mitte, wechseln.",
    ],
    tips: [
      "Lendenbereich darf den Boden nie verlassen.",
      "Langsam und kontrolliert.",
    ],
    calories_per_minute: 4,
  },
  {
    id: "side-plank",
    name: "Seitstütz",
    muscle_group: "Core",
    secondary_muscles: ["Schultern", "Gesäß"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Seitliche Bauchmuskulatur — für eine starke, stabile Mitte.",
    steps: [
      "Seitlich auf dem Unterarm liegen.",
      "Körper vom Boden heben — gerade Linie von Kopf bis Fuß.",
      "Hüfte nicht durchhängen lassen.",
      "Position halten.",
    ],
    tips: [
      "Freien Arm zur Decke strecken für mehr Stabilität.",
      "Mit Hüftdip für mehr Intensität.",
    ],
    calories_per_minute: 4,
  },
  {
    id: "v-sit",
    name: "V-Sit",
    muscle_group: "Core",
    secondary_muscles: ["Hüftbeuger"],
    equipment: "Kein Equipment",
    difficulty: "Mittel",
    description: "Ober- und Unterbauch gleichzeitig — volle Core-Aktivierung.",
    steps: [
      "Auf dem Gesäß balancieren.",
      "Beine und Oberkörper gleichzeitig heben.",
      "V-Form halten, Arme gestreckt nach vorne.",
      "Position halten oder auf- und absenken.",
    ],
    tips: [
      "Schwierig — mit Beinen leicht gebeugt starten.",
    ],
    calories_per_minute: 6,
  },

  // ── KARDIO (erweitert) ─────────────────────────────────────────
  {
    id: "jump-rope",
    name: "Seilspringen",
    muscle_group: "Kardio",
    secondary_muscles: ["Beine", "Schultern", "Core"],
    equipment: "Kein Equipment",
    difficulty: "Anfänger",
    description: "Bestes Ganzkörper-Kardio — hochkalorisch und koordinationsfördernd.",
    steps: [
      "Seil schulterbreit halten.",
      "Leicht auf den Fußballen stehen.",
      "Gleichmäßiger Rhythmus, kleine Sprünge.",
      "Handgelenke drehen das Seil — nicht die Arme.",
    ],
    tips: [
      "Mit 30 Sek an / 30 Sek Pause starten.",
      "Höher als 3 cm springen ist unnötig.",
    ],
    calories_per_minute: 12,
  },
  {
    id: "rowing-machine",
    name: "Ruderergometer",
    muscle_group: "Kardio",
    secondary_muscles: ["Rücken", "Beine", "Core"],
    equipment: "Maschine",
    difficulty: "Mittel",
    description: "Ganzkörper-Kardio mit starkem Rücken- und Beinanteil.",
    steps: [
      "Füße in die Halterungen spannen.",
      "Griff mit beiden Händen.",
      "Start: Beine drücken, dann Rücken zurücklehnen, dann Arme ziehen.",
      "Rückweg: Arme zuerst, dann Oberkörper, dann Beine.",
    ],
    tips: [
      "Rücken gerade — Überkopfneigen vermeiden.",
      "Gleichmäßiger Rhythmus wichtiger als Schnelligkeit.",
    ],
    calories_per_minute: 11,
  },
  {
    id: "box-jump",
    name: "Box Jump",
    muscle_group: "Kardio",
    secondary_muscles: ["Beine", "Gesäß"],
    equipment: "Kein Equipment",
    difficulty: "Mittel",
    description: "Explosivkraft und Schnellkraft — Athletentraining.",
    steps: [
      "Vor der Box stehen, Knie leicht gebeugt.",
      "Explosiv abspringen — Arme schwingen mit.",
      "Weich auf der Box landen — Knie leicht gebeugt.",
      "Aufrecht stellen.",
      "Kontrolliert herunterspringen oder -steigen.",
    ],
    tips: [
      "Weiche Landung immer wichtiger als Höhe.",
      "Mit niedriger Box beginnen.",
    ],
    calories_per_minute: 12,
  },
  {
    id: "burpee",
    name: "Burpees",
    muscle_group: "Kardio",
    secondary_muscles: ["Brust", "Beine", "Core"],
    equipment: "Kein Equipment",
    difficulty: "Mittel",
    description: "Härteste Körpergewichtsübung — maximaler Kalorienverbrauch.",
    steps: [
      "Aufrecht stehen.",
      "In den Liegestütz springen.",
      "Einen Liegestütz machen.",
      "Sprung zurück in den Stand.",
      "Sprung nach oben mit ausgestreckten Armen.",
    ],
    tips: [
      "Gleichmäßiges Tempo wichtiger als Schnelligkeit.",
      "Liegestütz kann weggelassen werden für Einsteiger.",
    ],
    calories_per_minute: 13,
  },
  {
    id: "stair-climber",
    name: "Stair Climber / Treppensteigen",
    muscle_group: "Kardio",
    secondary_muscles: ["Beine", "Gesäß"],
    equipment: "Maschine",
    difficulty: "Anfänger",
    description: "Gelenkschonend und hochkalorisch — ideal für Fettverbrennung.",
    steps: [
      "Stepper oder Treppe nutzen.",
      "Aufrechte Haltung, nicht abstützen.",
      "Gleichmäßiges Tempo.",
    ],
    tips: [
      "Nicht an den Handläufen stützen — reduziert den Effekt.",
      "Je langsamer, desto mehr Gesäß.",
    ],
    calories_per_minute: 9,
  },
];

export const MUSCLE_GROUPS = [
  { name: "Brust", icon: "🫁", color: "#E24B4A" },
  { name: "Rücken", icon: "🏋️", color: "#378ADD" },
  { name: "Schultern", icon: "🎯", color: "#EF9F27" },
  { name: "Bizeps", icon: "💪", color: "#1D9E75" },
  { name: "Trizeps", icon: "🔱", color: "#5DCAA5" },
  { name: "Beine", icon: "🦵", color: "#7F77DD" },
  { name: "Gesäß", icon: "🍑", color: "#D4537E" },
  { name: "Core", icon: "⚡", color: "#EF9F27" },
  { name: "Kardio", icon: "❤️", color: "#E24B4A" },
];
