export interface RecipeData {
  title: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  duration: number;
  servings: number;
  tags: string[];
  ingredients: { name: string; amount: string }[];
  steps: string[];
}

export const RECIPES: RecipeData[] = [
  {
    title: "Hähnchenbrust mit Süßkartoffel und Brokkoli",
    description: "Das klassische Fitness-Gericht — viel Protein, gute Carbs, wenig Fett.",
    calories: 450, protein: 48, carbs: 38, fat: 8,
    duration: 30, servings: 1,
    tags: ["High-Protein", "Mittagessen", "Abendessen", "Meal-Prep"],
    ingredients: [
      { name: "Hähnchenbrust", amount: "200g" },
      { name: "Süßkartoffel", amount: "200g" },
      { name: "Brokkoli", amount: "200g" },
      { name: "Olivenöl", amount: "1 TL" },
      { name: "Knoblauch", amount: "2 Zehen" },
      { name: "Salz, Pfeffer, Paprikapulver", amount: "nach Geschmack" },
    ],
    steps: [
      "Süßkartoffel schälen, in 2 cm Würfel schneiden, mit etwas Olivenöl und Salz bei 200°C 20 Min backen.",
      "Hähnchenbrust mit Salz, Pfeffer und Paprikapulver würzen.",
      "In einer Pfanne mit 1 TL Olivenöl bei mittlerer Hitze 6–7 Min pro Seite braten.",
      "Brokkoli in Röschen teilen, 5 Min in kochendem Salzwasser garen oder dämpfen.",
      "Alles zusammen servieren, nach Belieben mit frischem Knoblauch würzen.",
    ],
  },
  {
    title: "Lachs mit Quinoa und Spinat",
    description: "Omega-3-reich, proteingeladen und in 25 Minuten fertig.",
    calories: 520, protein: 42, carbs: 32, fat: 22,
    duration: 25, servings: 1,
    tags: ["High-Protein", "Omega-3", "Abendessen", "Gesund"],
    ingredients: [
      { name: "Lachsfilet", amount: "180g" },
      { name: "Quinoa (trocken)", amount: "80g" },
      { name: "Frischer Spinat", amount: "100g" },
      { name: "Zitrone", amount: "½ Stück" },
      { name: "Knoblauch", amount: "1 Zehe" },
      { name: "Olivenöl", amount: "1 EL" },
    ],
    steps: [
      "Quinoa mit doppelter Menge Wasser aufkochen, 15 Min köcheln lassen, quellen lassen.",
      "Lachs mit Salz, Pfeffer und Zitronensaft würzen.",
      "Pfanne erhitzen, Lachs mit Haut nach unten 4 Min braten, wenden, weitere 3 Min.",
      "In derselben Pfanne Knoblauch kurz anschwitzen, Spinat zugeben und 2 Min zusammenfallen lassen.",
      "Quinoa mit Spinat mischen, Lachs darauf legen, mit Zitrone servieren.",
    ],
  },
  {
    title: "Griechische Joghurt-Bowl mit Beeren",
    description: "Perfektes Frühstück — high protein, low calorie, in 5 Minuten fertig.",
    calories: 280, protein: 22, carbs: 28, fat: 4,
    duration: 5, servings: 1,
    tags: ["Frühstück", "Low-Calorie", "High-Protein", "Schnell", "Vegetarisch"],
    ingredients: [
      { name: "Griechischer Joghurt (0%)", amount: "200g" },
      { name: "Erdbeeren", amount: "100g" },
      { name: "Heidelbeeren", amount: "50g" },
      { name: "Chiasamen", amount: "1 EL (10g)" },
      { name: "Honig", amount: "1 TL" },
    ],
    steps: [
      "Griechischen Joghurt in eine Bowl geben.",
      "Erdbeeren vierteln, mit Heidelbeeren auf dem Joghurt verteilen.",
      "Chiasamen darüberstreuen.",
      "Mit einem Teelöffel Honig beträufeln.",
    ],
  },
  {
    title: "Omelette mit Spinat und Feta",
    description: "Proteinreiches Frühstück oder leichtes Abendessen in 10 Minuten.",
    calories: 320, protein: 28, carbs: 4, fat: 21,
    duration: 10, servings: 1,
    tags: ["Frühstück", "Low-Carb", "Vegetarisch", "Schnell"],
    ingredients: [
      { name: "Eier", amount: "3 Stück" },
      { name: "Frischer Spinat", amount: "80g" },
      { name: "Feta", amount: "40g" },
      { name: "Olivenöl", amount: "1 TL" },
      { name: "Salz, Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Eier mit Salz und Pfeffer verquirlen.",
      "Olivenöl in Pfanne erhitzen, Spinat 1 Min anschwitzen.",
      "Eimasse über den Spinat gießen.",
      "Feta zerbröseln und auf einer Hälfte verteilen.",
      "Omelette zusammenklappen, 2 Min weitergaren.",
    ],
  },
  {
    title: "Putenbrust mit Reis und Gemüse",
    description: "Mageres Protein mit komplexen Carbs — ideal für Muskelaufbau.",
    calories: 420, protein: 45, carbs: 42, fat: 5,
    duration: 25, servings: 1,
    tags: ["High-Protein", "Mittagessen", "Meal-Prep", "Low-Fat"],
    ingredients: [
      { name: "Putenbrust", amount: "200g" },
      { name: "Weißer Reis (trocken)", amount: "80g" },
      { name: "Paprika rot", amount: "1 Stück" },
      { name: "Zucchini", amount: "100g" },
      { name: "Zwiebel", amount: "½ Stück" },
      { name: "Olivenöl", amount: "1 TL" },
      { name: "Kurkuma, Salz, Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen (ca. 15–18 Min).",
      "Putenbrust in Scheiben schneiden, würzen.",
      "In Pfanne mit 1 TL Öl 4 Min pro Seite braten, beiseitestellen.",
      "Gemüse in derselben Pfanne 5 Min anbraten.",
      "Alles zusammen anrichten.",
    ],
  },
  {
    title: "Thunfisch-Salat mit Kichererbsen",
    description: "Proteinbombe ohne Kochen — perfekt für schnelle Mahlzeiten.",
    calories: 380, protein: 38, carbs: 30, fat: 10,
    duration: 10, servings: 1,
    tags: ["High-Protein", "Mittagessen", "Schnell", "Low-Carb"],
    ingredients: [
      { name: "Thunfisch (Dose, Wasser)", amount: "185g Dose" },
      { name: "Kichererbsen (Dose)", amount: "120g" },
      { name: "Gurke", amount: "½ Stück" },
      { name: "Tomate", amount: "1 Stück" },
      { name: "Rote Zwiebel", amount: "¼ Stück" },
      { name: "Olivenöl", amount: "1 EL" },
      { name: "Zitronensaft", amount: "1 EL" },
    ],
    steps: [
      "Thunfisch abtropfen lassen, in Schüssel geben.",
      "Kichererbsen abtropfen und abspülen.",
      "Gurke, Tomate und Zwiebel klein schneiden.",
      "Alles mischen, mit Öl, Zitrone, Salz und Pfeffer anmachen.",
    ],
  },
  {
    title: "Overnight Oats mit Protein",
    description: "Abends 5 Min vorbereiten, morgens fertig — reich an Protein und Ballaststoffen.",
    calories: 390, protein: 28, carbs: 48, fat: 8,
    duration: 5, servings: 1,
    tags: ["Frühstück", "Meal-Prep", "Vegetarisch", "Schnell"],
    ingredients: [
      { name: "Haferflocken", amount: "60g" },
      { name: "Magerquark", amount: "100g" },
      { name: "Mandelmilch (ungesüßt)", amount: "150ml" },
      { name: "Whey Protein (Vanille)", amount: "20g" },
      { name: "Banane", amount: "½ Stück" },
      { name: "Chiasamen", amount: "1 TL" },
    ],
    steps: [
      "Haferflocken, Quark, Mandelmilch und Protein in ein Glas geben.",
      "Gut umrühren bis alles vermischt ist.",
      "Chiasamen einrühren.",
      "Abgedeckt über Nacht in den Kühlschrank stellen.",
      "Morgens mit Bananenscheiben toppen.",
    ],
  },
  {
    title: "Hüttenkäse-Bowl mit Gurke und Lachs",
    description: "Leicht, proteinreich, kalorienarm — perfekter Snack oder Abendessen.",
    calories: 290, protein: 35, carbs: 6, fat: 13,
    duration: 5, servings: 1,
    tags: ["High-Protein", "Low-Carb", "Snack", "Abendessen", "Schnell"],
    ingredients: [
      { name: "Hüttenkäse", amount: "200g" },
      { name: "Räucherlachs", amount: "80g" },
      { name: "Gurke", amount: "½ Stück" },
      { name: "Dill", amount: "nach Geschmack" },
      { name: "Zitronensaft", amount: "1 TL" },
    ],
    steps: [
      "Hüttenkäse in eine Schüssel geben.",
      "Gurke würfeln, über den Hüttenkäse geben.",
      "Räucherlachs in Streifen darauflegen.",
      "Mit Dill und Zitronensaft würzen.",
    ],
  },
  {
    title: "Rinderhackfleisch-Bowl mit Reis",
    description: "Kalorienreichere Mahlzeit für Sportler — viel Protein und gute Carbs.",
    calories: 560, protein: 42, carbs: 50, fat: 18,
    duration: 20, servings: 1,
    tags: ["High-Protein", "Mittagessen", "Abendessen", "Meal-Prep"],
    ingredients: [
      { name: "Rinderhackfleisch (5% Fett)", amount: "200g" },
      { name: "Weißer Reis (trocken)", amount: "80g" },
      { name: "Zwiebel", amount: "½ Stück" },
      { name: "Knoblauch", amount: "2 Zehen" },
      { name: "Tomatenmark", amount: "1 EL" },
      { name: "Paprikapulver, Salz, Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Reis kochen.",
      "Zwiebel und Knoblauch würfeln, in Pfanne anschwitzen.",
      "Hackfleisch zugeben, 5–7 Min krümelig anbraten.",
      "Tomatenmark und Gewürze einrühren, 2 Min mitbraten.",
      "Mit Reis servieren.",
    ],
  },
  {
    title: "Veganer Protein-Smoothie",
    description: "Schnelle Post-Workout Mahlzeit mit Früchten und veganem Protein.",
    calories: 340, protein: 28, carbs: 42, fat: 6,
    duration: 3, servings: 1,
    tags: ["Frühstück", "Snack", "Vegan", "Post-Workout", "Schnell"],
    ingredients: [
      { name: "Banane (gefroren)", amount: "1 Stück" },
      { name: "Hafermilch", amount: "250ml" },
      { name: "Veganes Protein (Schokolade)", amount: "30g" },
      { name: "Erdnussbutter", amount: "1 EL" },
      { name: "Kakao (ungesüßt)", amount: "1 TL" },
    ],
    steps: [
      "Alle Zutaten in einen Mixer geben.",
      "30 Sekunden auf höchster Stufe mixen.",
      "In ein Glas gießen und sofort trinken.",
    ],
  },
  {
    title: "Garnelen mit Zucchini-Nudeln",
    description: "Low-Carb Alternative zu Pasta — leicht, lecker, sättigend.",
    calories: 280, protein: 32, carbs: 10, fat: 12,
    duration: 15, servings: 1,
    tags: ["Low-Carb", "High-Protein", "Abendessen", "Keto-freundlich"],
    ingredients: [
      { name: "Garnelen (geschält)", amount: "200g" },
      { name: "Zucchini", amount: "2 Stück (ca. 400g)" },
      { name: "Knoblauch", amount: "3 Zehen" },
      { name: "Olivenöl", amount: "1 EL" },
      { name: "Chili", amount: "nach Geschmack" },
      { name: "Zitronensaft", amount: "1 EL" },
      { name: "Petersilie", amount: "nach Geschmack" },
    ],
    steps: [
      "Zucchini mit einem Spiralschneider oder Sparschäler in Nudeln schneiden.",
      "Knoblauch und Chili in Olivenöl 1 Min anschwitzen.",
      "Garnelen zugeben, 2–3 Min von jeder Seite braten.",
      "Zucchini-Nudeln 2 Min mitbraten.",
      "Mit Zitronensaft und Petersilie servieren.",
    ],
  },
  {
    title: "Linsen-Suppe",
    description: "Herzhaft, sättigend, reich an pflanzlichem Protein und Ballaststoffen.",
    calories: 320, protein: 18, carbs: 48, fat: 5,
    duration: 35, servings: 2,
    tags: ["Vegan", "Vegetarisch", "Mittagessen", "Meal-Prep", "Günstig"],
    ingredients: [
      { name: "Rote Linsen", amount: "200g" },
      { name: "Karotte", amount: "2 Stück" },
      { name: "Sellerie (Stange)", amount: "2 Stangen" },
      { name: "Zwiebel", amount: "1 Stück" },
      { name: "Knoblauch", amount: "3 Zehen" },
      { name: "Tomatenmark", amount: "2 EL" },
      { name: "Gemüsebrühe", amount: "1 Liter" },
      { name: "Kreuzkümmel, Kurkuma", amount: "je 1 TL" },
    ],
    steps: [
      "Zwiebel und Knoblauch würfeln, in Olivenöl anschwitzen.",
      "Karotten und Sellerie würfeln, zugeben und 3 Min mitbraten.",
      "Tomatenmark und Gewürze einrühren.",
      "Linsen und Brühe zugeben, aufkochen.",
      "20–25 Min köcheln lassen bis Linsen weich sind.",
      "Mit Stabmixer leicht pürieren oder so lassen.",
    ],
  },
  {
    title: "Hähnchen-Stir-Fry mit Brokkoli",
    description: "Asiatisch inspiriert, schnell und proteinreich.",
    calories: 380, protein: 42, carbs: 18, fat: 12,
    duration: 15, servings: 1,
    tags: ["High-Protein", "Low-Carb", "Abendessen", "Schnell", "Asian"],
    ingredients: [
      { name: "Hähnchenbrust", amount: "200g" },
      { name: "Brokkoli", amount: "200g" },
      { name: "Karotte", amount: "1 Stück" },
      { name: "Paprika", amount: "1 Stück" },
      { name: "Sojasoße", amount: "2 EL" },
      { name: "Sesamöl", amount: "1 TL" },
      { name: "Ingwer", amount: "1 TL (gerieben)" },
      { name: "Knoblauch", amount: "2 Zehen" },
    ],
    steps: [
      "Hähnchen in dünne Streifen schneiden.",
      "Wok oder Pfanne sehr heiß erhitzen, Hähnchen 3–4 Min scharf anbraten, beiseitestellen.",
      "Gemüse im Wok 3–4 Min auf hoher Hitze braten.",
      "Hähnchen zurück, Sojasoße, Ingwer und Knoblauch zugeben.",
      "1–2 Min alles schwenken, mit Sesamöl beträufeln.",
    ],
  },
  {
    title: "Avocado-Toast mit pochiertem Ei",
    description: "Trendfrühstück mit gesunden Fetten und hochwertigem Protein.",
    calories: 390, protein: 16, carbs: 32, fat: 22,
    duration: 12, servings: 1,
    tags: ["Frühstück", "Vegetarisch", "Gesund"],
    ingredients: [
      { name: "Vollkornbrot", amount: "2 Scheiben" },
      { name: "Avocado (reif)", amount: "1 Stück" },
      { name: "Eier", amount: "2 Stück" },
      { name: "Zitronensaft", amount: "1 TL" },
      { name: "Chiliflocken", amount: "nach Geschmack" },
      { name: "Salz, Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Brot toasten.",
      "Avocado halbieren, Kern entfernen, Fruchtfleisch mit Gabel zerdrücken.",
      "Mit Zitronensaft, Salz und Pfeffer würzen.",
      "Wasser mit Schuss Essig köcheln, Eier einzeln reinschlagen, 3–4 Min pochieren.",
      "Avocado auf Toast streichen, Eier darauflegen, mit Chiliflocken bestreuen.",
    ],
  },
  {
    title: "Edamame-Bowl mit Tofu",
    description: "Vollständig pflanzliches Protein-Powerhouse.",
    calories: 420, protein: 32, carbs: 35, fat: 16,
    duration: 20, servings: 1,
    tags: ["Vegan", "High-Protein", "Mittagessen", "Asiatisch"],
    ingredients: [
      { name: "Tofu (fest)", amount: "200g" },
      { name: "Edamame (geschält)", amount: "100g" },
      { name: "Brauner Reis (trocken)", amount: "70g" },
      { name: "Gurke", amount: "½ Stück" },
      { name: "Sojasoße", amount: "2 EL" },
      { name: "Sesamöl", amount: "1 TL" },
      { name: "Sesam", amount: "1 TL" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Tofu in Würfel schneiden, in Pfanne ohne Öl 5 Min kross braten, Sojasoße zugeben.",
      "Edamame 3 Min in kochendem Wasser garen.",
      "Reis in Bowl, Tofu und Edamame darauf, Gurke in Scheiben dazu.",
      "Mit Sesamöl und Sesam beträufeln.",
    ],
  },
  {
    title: "Kichererbsen-Curry",
    description: "Würziges, veganes Curry — günstig, sättigend und nährstoffreich.",
    calories: 380, protein: 16, carbs: 55, fat: 10,
    duration: 25, servings: 2,
    tags: ["Vegan", "Vegetarisch", "Mittagessen", "Meal-Prep", "Asiatisch"],
    ingredients: [
      { name: "Kichererbsen (Dose)", amount: "400g" },
      { name: "Kokosmilch (Dose)", amount: "200ml" },
      { name: "Tomaten (Dose)", amount: "400g" },
      { name: "Zwiebel", amount: "1 Stück" },
      { name: "Knoblauch", amount: "3 Zehen" },
      { name: "Ingwer (frisch)", amount: "2 cm" },
      { name: "Curry-Pulver", amount: "2 TL" },
      { name: "Garam Masala", amount: "1 TL" },
    ],
    steps: [
      "Zwiebel, Knoblauch und Ingwer würfeln, in Öl anschwitzen.",
      "Gewürze zugeben, 1 Min anrösten.",
      "Tomaten und Kichererbsen (abgetropft) zugeben.",
      "15 Min köcheln lassen.",
      "Kokosmilch einrühren, weitere 5 Min köcheln.",
      "Mit Reis oder Naan servieren.",
    ],
  },
  {
    title: "Lachs-Teriyaki mit Pak Choi",
    description: "Japanisch inspiriert — süß-salzig glasierter Lachs mit Blattgemüse.",
    calories: 430, protein: 38, carbs: 22, fat: 20,
    duration: 20, servings: 1,
    tags: ["High-Protein", "Omega-3", "Abendessen", "Asiatisch"],
    ingredients: [
      { name: "Lachsfilet", amount: "200g" },
      { name: "Pak Choi", amount: "2 Köpfe" },
      { name: "Sojasoße", amount: "3 EL" },
      { name: "Honig", amount: "1 EL" },
      { name: "Sesamöl", amount: "1 TL" },
      { name: "Knoblauch", amount: "2 Zehen" },
      { name: "Sesam", amount: "1 TL" },
    ],
    steps: [
      "Sojasoße, Honig und Knoblauch mischen — Teriyaki-Sauce.",
      "Lachs 10 Min in der Hälfte der Sauce marinieren.",
      "Lachs bei mittlerer Hitze 4 Min pro Seite braten, restliche Sauce zugeben und einkochen.",
      "Pak Choi halbieren, in Sesamöl 3 Min anbraten.",
      "Mit Sesam garnieren.",
    ],
  },
  {
    title: "Eiweißpfannkuchen",
    description: "Fluffige Protein-Pancakes ohne viel Zucker — perfektes Fitness-Frühstück.",
    calories: 320, protein: 32, carbs: 28, fat: 8,
    duration: 15, servings: 1,
    tags: ["Frühstück", "High-Protein", "Vegetarisch"],
    ingredients: [
      { name: "Eier", amount: "2 Stück" },
      { name: "Magerquark", amount: "100g" },
      { name: "Haferflocken (fein)", amount: "40g" },
      { name: "Whey Protein (Vanille)", amount: "15g" },
      { name: "Backpulver", amount: "½ TL" },
      { name: "Zimt", amount: "½ TL" },
    ],
    steps: [
      "Alle Zutaten in einer Schüssel glatt rühren.",
      "Teig 2 Min quellen lassen.",
      "Pfanne bei mittlerer Hitze mit etwas Kokosöl erhitzen.",
      "Je 2–3 EL Teig einlöffeln, 2–3 Min backen bis Blasen aufsteigen.",
      "Wenden, weitere 1–2 Min backen.",
      "Mit griechischem Joghurt und frischen Beeren servieren.",
    ],
  },
  {
    title: "Rinderfilet mit Spargel",
    description: "Premium-Mahlzeit für Muskelaufbau — mageres Rindfleisch mit Vitaminen.",
    calories: 380, protein: 42, carbs: 8, fat: 18,
    duration: 20, servings: 1,
    tags: ["High-Protein", "Low-Carb", "Abendessen", "Premium"],
    ingredients: [
      { name: "Rinderfilet", amount: "180g" },
      { name: "Grüner Spargel", amount: "250g" },
      { name: "Butter", amount: "1 TL" },
      { name: "Olivenöl", amount: "1 EL" },
      { name: "Knoblauch", amount: "2 Zehen" },
      { name: "Salz, Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Fleisch 30 Min vor dem Braten aus dem Kühlschrank nehmen.",
      "Pfanne sehr heiß erhitzen (hohe Hitze), Öl zugeben.",
      "Steak 2–3 Min pro Seite für medium braten.",
      "Butter und Knoblauch zugeben, Fleisch damit übergießen.",
      "5 Min ruhen lassen.",
      "Spargel in derselben Pfanne 5 Min braten.",
    ],
  },
  {
    title: "Veganer Quinoa-Salat",
    description: "Vollständig veganer Salat mit allen essentiellen Aminosäuren.",
    calories: 350, protein: 14, carbs: 48, fat: 12,
    duration: 20, servings: 1,
    tags: ["Vegan", "Vegetarisch", "Mittagessen", "Salat"],
    ingredients: [
      { name: "Quinoa (trocken)", amount: "80g" },
      { name: "Paprika rot", amount: "1 Stück" },
      { name: "Gurke", amount: "½ Stück" },
      { name: "Tomate", amount: "1 Stück" },
      { name: "Rote Zwiebel", amount: "¼ Stück" },
      { name: "Petersilie", amount: "1 Bund" },
      { name: "Olivenöl", amount: "2 EL" },
      { name: "Zitronensaft", amount: "2 EL" },
    ],
    steps: [
      "Quinoa nach Packungsanweisung kochen, abkühlen lassen.",
      "Gemüse in kleine Würfel schneiden.",
      "Petersilie fein hacken.",
      "Alles mischen.",
      "Mit Olivenöl, Zitronensaft, Salz und Pfeffer anmachen.",
    ],
  },
  {
    title: "Hähnchen-Wraps mit Hummus",
    description: "Schnelle Mittagsmahlzeit zum Mitnehmen.",
    calories: 480, protein: 38, carbs: 42, fat: 14,
    duration: 15, servings: 1,
    tags: ["High-Protein", "Mittagessen", "Schnell", "To-Go"],
    ingredients: [
      { name: "Hähnchenbrust (vorgegart)", amount: "150g" },
      { name: "Vollkorn-Tortilla", amount: "2 Stück" },
      { name: "Hummus", amount: "60g" },
      { name: "Eisbergsalat", amount: "2 Blätter" },
      { name: "Tomate", amount: "1 Stück" },
      { name: "Gurke", amount: "¼ Stück" },
    ],
    steps: [
      "Hähnchen in Streifen schneiden.",
      "Tortilla mit Hummus bestreichen.",
      "Salat, Tomate, Gurke und Hähnchen belegen.",
      "Fest einrollen.",
    ],
  },
  {
    title: "Magerquark mit Beeren und Nüssen",
    description: "Einfacher Snack oder Dessert mit viel Protein.",
    calories: 240, protein: 20, carbs: 20, fat: 7,
    duration: 3, servings: 1,
    tags: ["Snack", "Vegetarisch", "High-Protein", "Schnell"],
    ingredients: [
      { name: "Magerquark", amount: "200g" },
      { name: "Himbeeren", amount: "100g" },
      { name: "Walnüsse", amount: "15g" },
      { name: "Honig", amount: "1 TL" },
    ],
    steps: [
      "Magerquark in eine Schüssel geben.",
      "Himbeeren darauf verteilen.",
      "Walnüsse grob hacken und darüberstreuen.",
      "Mit Honig beträufeln.",
    ],
  },
  {
    title: "Brokkoli-Cremesuppe",
    description: "Cremig, sättigend, voller Vitamine — wenige Kalorien.",
    calories: 180, protein: 8, carbs: 20, fat: 7,
    duration: 25, servings: 2,
    tags: ["Vegetarisch", "Low-Calorie", "Mittagessen", "Meal-Prep"],
    ingredients: [
      { name: "Brokkoli", amount: "500g" },
      { name: "Kartoffel", amount: "2 Stück" },
      { name: "Zwiebel", amount: "1 Stück" },
      { name: "Gemüsebrühe", amount: "700ml" },
      { name: "Frischkäse (light)", amount: "50g" },
      { name: "Muskat, Salz, Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Brokkoli in Röschen, Kartoffeln und Zwiebel würfeln.",
      "Zwiebel anschwitzen, Kartoffeln 3 Min mitbraten.",
      "Brühe aufgießen, 15 Min köcheln.",
      "Brokkoli zugeben, weitere 5 Min garen.",
      "Mit Stabmixer pürieren, Frischkäse einrühren.",
      "Mit Muskat abschmecken.",
    ],
  },
  {
    title: "Spiegelei mit Vollkornbrot und Tomaten",
    description: "Schnelles, günstiges Frühstück mit ausgewogenen Makros.",
    calories: 290, protein: 16, carbs: 28, fat: 12,
    duration: 8, servings: 1,
    tags: ["Frühstück", "Vegetarisch", "Schnell", "Günstig"],
    ingredients: [
      { name: "Eier", amount: "2 Stück" },
      { name: "Vollkornbrot", amount: "2 Scheiben" },
      { name: "Tomate", amount: "1 Stück" },
      { name: "Olivenöl", amount: "1 TL" },
      { name: "Salz, Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Brot toasten.",
      "Olivenöl in Pfanne bei mittlerer Hitze erhitzen.",
      "Eier einschlagen, Deckel drauf, 3 Min braten.",
      "Mit Tomate, Salz und Pfeffer servieren.",
    ],
  },
  {
    title: "Süßkartoffel-Hähnchen-Bowl",
    description: "Meal-Prep Favorit — lässt sich 4 Tage im Kühlschrank aufbewahren.",
    calories: 490, protein: 44, carbs: 46, fat: 10,
    duration: 35, servings: 1,
    tags: ["High-Protein", "Meal-Prep", "Mittagessen", "Abendessen"],
    ingredients: [
      { name: "Hähnchenbrust", amount: "200g" },
      { name: "Süßkartoffel", amount: "250g" },
      { name: "Spinat", amount: "80g" },
      { name: "Avocado", amount: "½ Stück" },
      { name: "Olivenöl", amount: "1 EL" },
      { name: "Limettensaft", amount: "1 EL" },
    ],
    steps: [
      "Süßkartoffel würfeln, mit Olivenöl bei 200°C 25 Min backen.",
      "Hähnchen würzen, in Pfanne 12–14 Min garen, in Scheiben schneiden.",
      "Spinat in derselben Pfanne kurz zusammenfallen lassen.",
      "Bowl aufbauen: Süßkartoffel, Hähnchen, Spinat, Avocado.",
      "Mit Limettensaft beträufeln.",
    ],
  },
  {
    title: "Gebratener Tofu mit Erdnusssauce",
    description: "Veganes High-Protein Gericht mit cremiger Erdnusssauce.",
    calories: 440, protein: 24, carbs: 30, fat: 25,
    duration: 20, servings: 1,
    tags: ["Vegan", "High-Protein", "Abendessen", "Asiatisch"],
    ingredients: [
      { name: "Tofu (fest)", amount: "250g" },
      { name: "Erdnussbutter", amount: "2 EL" },
      { name: "Sojasoße", amount: "2 EL" },
      { name: "Limettensaft", amount: "1 EL" },
      { name: "Sriracha", amount: "nach Geschmack" },
      { name: "Knoblauch", amount: "1 Zehe" },
      { name: "Jasmin Reis", amount: "80g (trocken)" },
    ],
    steps: [
      "Tofu in Scheiben schneiden, mit Küchenpapier gut trockendrücken.",
      "In Pfanne ohne Öl 5 Min pro Seite kross braten.",
      "Erdnusssauce: Erdnussbutter, Sojasoße, Limette, Sriracha, Knoblauch und 2 EL Wasser verrühren.",
      "Reis kochen.",
      "Tofu mit Erdnusssauce übergießen, zu Reis servieren.",
    ],
  },
  {
    title: "Makrelen-Salat mit Rucola",
    description: "Omega-3-reich, schnell und kalorienarm.",
    calories: 310, protein: 28, carbs: 8, fat: 18,
    duration: 8, servings: 1,
    tags: ["High-Protein", "Low-Carb", "Mittagessen", "Schnell", "Omega-3"],
    ingredients: [
      { name: "Makrele (Dose)", amount: "130g" },
      { name: "Rucola", amount: "80g" },
      { name: "Tomate", amount: "1 Stück" },
      { name: "Rote Zwiebel", amount: "¼ Stück" },
      { name: "Olivenöl", amount: "1 EL" },
      { name: "Zitronensaft", amount: "1 EL" },
    ],
    steps: [
      "Rucola waschen, auf Teller verteilen.",
      "Tomate und Zwiebel in Scheiben schneiden.",
      "Makrele abtropfen lassen, auf Salat legen.",
      "Mit Olivenöl und Zitronensaft beträufeln.",
    ],
  },
  {
    title: "Chicken Caesar Salat",
    description: "Der Klassiker — leicht modifiziert für mehr Protein.",
    calories: 380, protein: 36, carbs: 14, fat: 20,
    duration: 15, servings: 1,
    tags: ["High-Protein", "Mittagessen", "Salat"],
    ingredients: [
      { name: "Hähnchenbrust (gegrillt)", amount: "150g" },
      { name: "Römersalat", amount: "150g" },
      { name: "Parmesan", amount: "20g" },
      { name: "Griechischer Joghurt (2%)", amount: "50g" },
      { name: "Zitronensaft", amount: "1 EL" },
      { name: "Senf", amount: "1 TL" },
      { name: "Knoblauch", amount: "1 Zehe" },
    ],
    steps: [
      "Dressing: Joghurt, Zitronensaft, Senf, Knoblauch (gepresst) verrühren.",
      "Salat waschen, in mundgerechte Stücke reißen.",
      "Hähnchen in Streifen schneiden.",
      "Salat mit Dressing mischen.",
      "Hähnchen darauflegen, mit geriebenem Parmesan bestreuen.",
    ],
  },
  {
    title: "Vollkorn-Pasta mit Hackfleisch",
    description: "Schnelle Bolognese mit gesunden Zutaten.",
    calories: 520, protein: 38, carbs: 52, fat: 14,
    duration: 25, servings: 1,
    tags: ["High-Protein", "Mittagessen", "Abendessen", "Schnell"],
    ingredients: [
      { name: "Vollkornnudeln (trocken)", amount: "100g" },
      { name: "Rinderhackfleisch (5% Fett)", amount: "150g" },
      { name: "Tomatensauce (passiert)", amount: "200ml" },
      { name: "Zwiebel", amount: "½ Stück" },
      { name: "Knoblauch", amount: "2 Zehen" },
      { name: "Olivenöl", amount: "1 TL" },
      { name: "Oregano, Basilikum", amount: "nach Geschmack" },
    ],
    steps: [
      "Nudeln nach Packung kochen.",
      "Zwiebel und Knoblauch anbraten.",
      "Hackfleisch zugeben, krümelig braten.",
      "Tomatensauce und Gewürze zugeben, 10 Min köcheln.",
      "Mit Nudeln servieren.",
    ],
  },
  {
    title: "Protein-Porridge",
    description: "Wärmendes Frühstück für kalte Tage — mit Protein angereichert.",
    calories: 360, protein: 26, carbs: 44, fat: 8,
    duration: 8, servings: 1,
    tags: ["Frühstück", "Vegetarisch", "High-Protein", "Warm"],
    ingredients: [
      { name: "Haferflocken", amount: "60g" },
      { name: "Vollmilch (1,5%)", amount: "200ml" },
      { name: "Whey Protein (Vanille)", amount: "20g" },
      { name: "Banane", amount: "½ Stück" },
      { name: "Zimt", amount: "½ TL" },
      { name: "Mandelmus", amount: "1 TL" },
    ],
    steps: [
      "Haferflocken mit Milch in einem Topf aufkochen.",
      "Auf mittlerer Hitze 3–4 Min rühren bis cremig.",
      "Vom Herd nehmen, Protein einrühren (nicht kochen).",
      "Mit Banane, Zimt und Mandelmus servieren.",
    ],
  },
  {
    title: "Gebackene Hähnchenschenkel",
    description: "Knusprig, saftig, einfach — perfekt für Familienmahlzeiten.",
    calories: 380, protein: 35, carbs: 2, fat: 25,
    duration: 45, servings: 2,
    tags: ["High-Protein", "Abendessen", "Meal-Prep"],
    ingredients: [
      { name: "Hähnchenschenkel", amount: "4 Stück (ca. 600g)" },
      { name: "Olivenöl", amount: "2 EL" },
      { name: "Paprikapulver (geräuchert)", amount: "1 TL" },
      { name: "Knoblauchpulver", amount: "1 TL" },
      { name: "Oregano", amount: "1 TL" },
      { name: "Salz, Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Ofen auf 200°C vorheizen.",
      "Hähnchenschenkel mit Olivenöl, Gewürzen rundum einreiben.",
      "Auf Backblech mit Backpapier legen.",
      "35–40 Min backen bis goldbraun und durchgegart.",
      "5 Min ruhen lassen.",
    ],
  },
  {
    title: "Schwarze Bohnen Tacos",
    description: "Schnelle vegane Tacos voller pflanzlichem Protein.",
    calories: 420, protein: 20, carbs: 58, fat: 12,
    duration: 15, servings: 1,
    tags: ["Vegan", "Vegetarisch", "Mittagessen", "Schnell"],
    ingredients: [
      { name: "Schwarze Bohnen (Dose)", amount: "240g" },
      { name: "Maistortillas", amount: "3 Stück" },
      { name: "Paprika", amount: "1 Stück" },
      { name: "Mais (Dose)", amount: "80g" },
      { name: "Rote Zwiebel", amount: "¼ Stück" },
      { name: "Guacamole", amount: "60g" },
      { name: "Kreuzkümmel, Chili", amount: "nach Geschmack" },
    ],
    steps: [
      "Bohnen abtropfen, mit Gewürzen in Pfanne 3 Min erwärmen.",
      "Paprika und Zwiebel würfeln.",
      "Tortillas in Pfanne ohne Öl 1 Min pro Seite erwärmen.",
      "Mit Bohnen, Gemüse, Mais und Guacamole belegen.",
    ],
  },
  {
    title: "Lachssuppe mit Kartoffeln",
    description: "Cremige skandinavische Suppe — Reich an Omega-3.",
    calories: 420, protein: 32, carbs: 28, fat: 20,
    duration: 30, servings: 2,
    tags: ["Omega-3", "Abendessen", "Meal-Prep", "Warm"],
    ingredients: [
      { name: "Lachs", amount: "300g" },
      { name: "Kartoffeln", amount: "3 Stück" },
      { name: "Sahne (15%)", amount: "100ml" },
      { name: "Fischbrühe", amount: "600ml" },
      { name: "Lauch", amount: "1 Stange" },
      { name: "Dill", amount: "1 Bund" },
      { name: "Butter", amount: "1 TL" },
    ],
    steps: [
      "Kartoffeln würfeln, Lauch in Ringe schneiden.",
      "Butter in Topf erhitzen, Lauch 3 Min anschwitzen.",
      "Brühe aufgießen, Kartoffeln zugeben, 15 Min kochen.",
      "Lachs in Würfel schneiden, zugeben, 5 Min ziehen lassen.",
      "Sahne einrühren, mit Dill und Salz abschmecken.",
    ],
  },
  {
    title: "Tempeh-Stir-Fry",
    description: "Fermentiertes Soja mit maximaler Proteinwirkung.",
    calories: 460, protein: 30, carbs: 40, fat: 18,
    duration: 20, servings: 1,
    tags: ["Vegan", "High-Protein", "Abendessen", "Asiatisch"],
    ingredients: [
      { name: "Tempeh", amount: "200g" },
      { name: "Brokkoli", amount: "150g" },
      { name: "Karotten", amount: "2 Stück" },
      { name: "Sojasoße", amount: "3 EL" },
      { name: "Sesamöl", amount: "1 EL" },
      { name: "Ingwer", amount: "1 TL" },
      { name: "Reis (trocken)", amount: "70g" },
    ],
    steps: [
      "Reis kochen.",
      "Tempeh in Scheiben schneiden, in Sojasoße 5 Min marinieren.",
      "Wok erhitzen, Tempeh kross anbraten, beiseitestellen.",
      "Gemüse im Wok 4 Min braten.",
      "Tempeh zurück, Ingwer und Sesamöl zugeben.",
      "Zu Reis servieren.",
    ],
  },
  {
    title: "Käse-Omelette mit Champignons",
    description: "Herzhafte Mahlzeit mit wenigen Kohlenhydraten.",
    calories: 350, protein: 26, carbs: 6, fat: 25,
    duration: 10, servings: 1,
    tags: ["Frühstück", "Low-Carb", "Vegetarisch", "Schnell"],
    ingredients: [
      { name: "Eier", amount: "3 Stück" },
      { name: "Champignons", amount: "100g" },
      { name: "Gouda (gerieben)", amount: "30g" },
      { name: "Butter", amount: "1 TL" },
      { name: "Salz, Pfeffer, Schnittlauch", amount: "nach Geschmack" },
    ],
    steps: [
      "Champignons in Scheiben schneiden, in Butter 3 Min anbraten.",
      "Eier verquirlen, über Champignons gießen.",
      "Käse auf eine Hälfte streuen.",
      "Zusammenklappen, 2 Min fertigbacken.",
      "Mit Schnittlauch garnieren.",
    ],
  },
  {
    title: "Smoothie Bowl mit Açaí",
    description: "Antioxidantienreiche Bowl für einen energetischen Start.",
    calories: 380, protein: 12, carbs: 58, fat: 12,
    duration: 8, servings: 1,
    tags: ["Frühstück", "Vegan", "Vegetarisch", "Schnell"],
    ingredients: [
      { name: "Açaí-Püree (tiefgekühlt)", amount: "100g" },
      { name: "Banane (gefroren)", amount: "1 Stück" },
      { name: "Mandelmilch", amount: "60ml" },
      { name: "Granola", amount: "30g" },
      { name: "Erdbeeren", amount: "50g" },
      { name: "Chiasamen", amount: "1 TL" },
      { name: "Kokosflocken", amount: "1 TL" },
    ],
    steps: [
      "Açaí und Banane mit Mandelmilch mixen bis cremig (wenig Flüssigkeit — soll dick sein).",
      "In eine Bowl füllen.",
      "Mit Granola, Erdbeeren, Chiasamen und Kokosflocken toppen.",
    ],
  },
  {
    title: "Hähnchen-Gyros mit Tzatziki",
    description: "Griechischer Klassiker — proteinreich und aromatisch.",
    calories: 430, protein: 44, carbs: 22, fat: 16,
    duration: 25, servings: 1,
    tags: ["High-Protein", "Mittagessen", "Abendessen", "Griechisch"],
    ingredients: [
      { name: "Hähnchenbrust", amount: "200g" },
      { name: "Griechischer Joghurt (2%)", amount: "150g" },
      { name: "Gurke", amount: "½ Stück" },
      { name: "Knoblauch", amount: "2 Zehen" },
      { name: "Olivenöl", amount: "1 EL" },
      { name: "Oregano, Paprika, Kreuzkümmel", amount: "je ½ TL" },
      { name: "Vollkorn-Pita", amount: "1 Stück" },
    ],
    steps: [
      "Hähnchen in Streifen schneiden, mit Gewürzen und ½ EL Öl marinieren.",
      "In heißer Pfanne 6–8 Min kross braten.",
      "Tzatziki: Joghurt, Gurke (gerieben, ausgedrückt), Knoblauch, ½ EL Öl, Salz.",
      "Pita kurz erwärmen, mit Hähnchen und Tzatziki füllen.",
    ],
  },
  {
    title: "Rote Linsen-Dal",
    description: "Indisch gewürztes Dal — warm, sättigend, nährstoffreich.",
    calories: 350, protein: 18, carbs: 52, fat: 7,
    duration: 30, servings: 2,
    tags: ["Vegan", "Vegetarisch", "Mittagessen", "Meal-Prep", "Asiatisch"],
    ingredients: [
      { name: "Rote Linsen", amount: "200g" },
      { name: "Kokosmilch", amount: "150ml" },
      { name: "Tomaten (Dose)", amount: "200g" },
      { name: "Zwiebel", amount: "1 Stück" },
      { name: "Knoblauch", amount: "3 Zehen" },
      { name: "Ingwer", amount: "2 cm" },
      { name: "Garam Masala, Kurkuma, Kreuzkümmel", amount: "je 1 TL" },
    ],
    steps: [
      "Zwiebel, Knoblauch, Ingwer fein würfeln, in Öl anschwitzen.",
      "Gewürze 1 Min anrösten.",
      "Linsen, Tomaten und 300 ml Wasser zugeben.",
      "20 Min köcheln bis Linsen zerfallen.",
      "Kokosmilch einrühren, abschmecken.",
      "Mit Naan oder Reis servieren.",
    ],
  },
  {
    title: "Fitness-Frittata",
    description: "Im Ofen gebackenes Eiergericht — für Meal-Prep ideal.",
    calories: 290, protein: 24, carbs: 8, fat: 18,
    duration: 25, servings: 2,
    tags: ["Frühstück", "Meal-Prep", "Low-Carb", "Vegetarisch"],
    ingredients: [
      { name: "Eier", amount: "6 Stück" },
      { name: "Paprika", amount: "1 Stück" },
      { name: "Spinat", amount: "80g" },
      { name: "Feta", amount: "60g" },
      { name: "Champignons", amount: "100g" },
      { name: "Olivenöl", amount: "1 EL" },
    ],
    steps: [
      "Ofen auf 180°C vorheizen.",
      "Gemüse in oven-fester Pfanne 3 Min anbraten.",
      "Eier verquirlen, würzen, über Gemüse gießen.",
      "Feta zerbröseln darüber.",
      "15–18 Min im Ofen backen bis fest.",
      "In Portionen schneiden.",
    ],
  },
  {
    title: "Proteinreicher Hühnereintopf",
    description: "Gemüse-Hühner-Eintopf — wärmend und sättigend.",
    calories: 340, protein: 38, carbs: 22, fat: 8,
    duration: 40, servings: 2,
    tags: ["High-Protein", "Mittagessen", "Meal-Prep", "Warm"],
    ingredients: [
      { name: "Hähnchenbrust", amount: "300g" },
      { name: "Karotten", amount: "2 Stück" },
      { name: "Sellerie", amount: "2 Stangen" },
      { name: "Kartoffeln", amount: "2 Stück" },
      { name: "Zwiebel", amount: "1 Stück" },
      { name: "Hühnerbrühe", amount: "800ml" },
      { name: "Petersilie, Lorbeer", amount: "nach Geschmack" },
    ],
    steps: [
      "Gemüse würfeln.",
      "Brühe aufkochen, Hähnchen im Stück zugeben.",
      "20 Min garen, Hähnchen herausnehmen und zerzupfen.",
      "Gemüse in der Brühe 15 Min kochen.",
      "Hähnchen zurück, mit Petersilie abschmecken.",
    ],
  },
  {
    title: "Seitan-Gulasch",
    description: "Veganes Gulasch mit Seitan — überraschend fleischig im Biss.",
    calories: 380, protein: 42, carbs: 30, fat: 8,
    duration: 35, servings: 2,
    tags: ["Vegan", "High-Protein", "Abendessen"],
    ingredients: [
      { name: "Seitan", amount: "300g" },
      { name: "Paprika rot", amount: "2 Stück" },
      { name: "Zwiebel", amount: "2 Stück" },
      { name: "Tomatenmark", amount: "2 EL" },
      { name: "Paprikapulver (edelsüß und scharf)", amount: "je 1 TL" },
      { name: "Gemüsebrühe", amount: "300ml" },
    ],
    steps: [
      "Seitan in Stücke schneiden.",
      "Zwiebeln und Paprika würfeln, in Öl 5 Min anbraten.",
      "Tomatenmark und Paprikapulver einrühren, 1 Min rösten.",
      "Seitan zugeben, mit Brühe aufgießen.",
      "20 Min köcheln lassen.",
      "Mit Kartoffeln oder Knäckebrot servieren.",
    ],
  },
  {
    title: "Forelle aus dem Ofen",
    description: "Ganzer Fisch, einfach und elegant — voll mit Omega-3.",
    calories: 280, protein: 38, carbs: 2, fat: 12,
    duration: 30, servings: 1,
    tags: ["High-Protein", "Omega-3", "Low-Carb", "Abendessen"],
    ingredients: [
      { name: "Forelle (küchenfertig)", amount: "1 Stück (ca. 300g)" },
      { name: "Zitrone", amount: "1 Stück" },
      { name: "Knoblauch", amount: "3 Zehen" },
      { name: "Dill", amount: "1 Bund" },
      { name: "Olivenöl", amount: "1 EL" },
    ],
    steps: [
      "Ofen auf 180°C vorheizen.",
      "Forelle innen und außen salzen und pfeffern.",
      "Mit Zitronenscheiben, Knoblauch und Dill füllen.",
      "Mit Olivenöl bestreichen.",
      "20–25 Min im Ofen backen.",
    ],
  },
  {
    title: "Reissalat mit Thunfisch",
    description: "Einfaches Meal-Prep für die Woche — hält 3 Tage im Kühlschrank.",
    calories: 400, protein: 32, carbs: 44, fat: 9,
    duration: 20, servings: 2,
    tags: ["High-Protein", "Meal-Prep", "Mittagessen", "Kalt"],
    ingredients: [
      { name: "Weißer Reis (trocken)", amount: "150g" },
      { name: "Thunfisch (Dose, Wasser)", amount: "2 Dosen (à 185g)" },
      { name: "Paprika", amount: "1 Stück" },
      { name: "Erbsen (Dose)", amount: "100g" },
      { name: "Mais (Dose)", amount: "80g" },
      { name: "Olivenöl", amount: "2 EL" },
      { name: "Essig, Salz, Pfeffer", amount: "nach Geschmack" },
    ],
    steps: [
      "Reis kochen, abkühlen lassen.",
      "Thunfisch abtropfen lassen.",
      "Paprika würfeln, Erbsen und Mais abgießen.",
      "Alles mischen.",
      "Mit Öl, Essig, Salz und Pfeffer anmachen.",
    ],
  },
  {
    title: "Skyr mit Erdbeeren und Granola",
    description: "Isländischer Frischkäse-Snack mit maximaler Protein-Dichte.",
    calories: 250, protein: 20, carbs: 28, fat: 4,
    duration: 3, servings: 1,
    tags: ["Frühstück", "Snack", "High-Protein", "Schnell", "Vegetarisch"],
    ingredients: [
      { name: "Skyr (natur)", amount: "200g" },
      { name: "Erdbeeren", amount: "100g" },
      { name: "Granola", amount: "20g" },
      { name: "Honig", amount: "1 TL" },
    ],
    steps: [
      "Skyr in Schüssel geben.",
      "Erdbeeren halbieren und darüber verteilen.",
      "Granola aufstreuen.",
      "Mit Honig beträufeln.",
    ],
  },
  {
    title: "Mediterranes Gemüse vom Blech",
    description: "Buntes Ofengemüse als Beilage oder vegane Hauptmahlzeit.",
    calories: 220, protein: 6, carbs: 28, fat: 10,
    duration: 35, servings: 2,
    tags: ["Vegan", "Vegetarisch", "Beilage", "Meal-Prep"],
    ingredients: [
      { name: "Zucchini", amount: "2 Stück" },
      { name: "Aubergine", amount: "1 Stück" },
      { name: "Paprika", amount: "2 Stück" },
      { name: "Tomate", amount: "3 Stück" },
      { name: "Olivenöl", amount: "3 EL" },
      { name: "Oregano, Thymian, Knoblauch", amount: "nach Geschmack" },
    ],
    steps: [
      "Ofen auf 200°C vorheizen.",
      "Gemüse in grobe Stücke schneiden.",
      "Mit Olivenöl, Gewürzen und Knoblauch vermengen.",
      "Auf Backblech verteilen.",
      "25–30 Min backen bis leicht geröstet.",
    ],
  },
  {
    title: "Hähnchen-Tacos mit Mango-Salsa",
    description: "Fruchtig-würzige Kombination für sommerliche Mahlzeiten.",
    calories: 460, protein: 38, carbs: 46, fat: 12,
    duration: 20, servings: 1,
    tags: ["High-Protein", "Mittagessen", "Abendessen", "Fruchtig"],
    ingredients: [
      { name: "Hähnchenbrust", amount: "180g" },
      { name: "Maistortillas", amount: "3 Stück" },
      { name: "Mango", amount: "½ Stück" },
      { name: "Rote Zwiebel", amount: "¼ Stück" },
      { name: "Koriander", amount: "nach Geschmack" },
      { name: "Limettensaft", amount: "2 EL" },
      { name: "Chili", amount: "nach Geschmack" },
    ],
    steps: [
      "Hähnchen würzen und in Pfanne 12–14 Min garen, zerzupfen.",
      "Mango-Salsa: Mango fein würfeln, Zwiebel, Koriander, Limette, Chili mischen.",
      "Tortillas erwärmen.",
      "Mit Hähnchen und Mango-Salsa belegen.",
    ],
  },
  {
    title: "Spinat-Shakshuka",
    description: "Eier in Tomatensauce — proteinreich, würzig, sättigend.",
    calories: 310, protein: 22, carbs: 20, fat: 16,
    duration: 20, servings: 2,
    tags: ["Vegetarisch", "Frühstück", "Abendessen", "Warm"],
    ingredients: [
      { name: "Eier", amount: "4 Stück" },
      { name: "Tomaten (Dose)", amount: "400g" },
      { name: "Spinat", amount: "100g" },
      { name: "Zwiebel", amount: "1 Stück" },
      { name: "Knoblauch", amount: "3 Zehen" },
      { name: "Kreuzkümmel, Paprika, Chili", amount: "je ½ TL" },
    ],
    steps: [
      "Zwiebel und Knoblauch in Öl anschwitzen.",
      "Gewürze zugeben, 1 Min rösten.",
      "Tomaten zugeben, 10 Min köcheln.",
      "Spinat einrühren.",
      "Mulden in Sauce drücken, Eier einschlagen.",
      "Deckel drauf, 5–7 Min stocken lassen.",
    ],
  },
  {
    title: "Garnelen-Bowl mit Avocado",
    description: "Leichte, proteinreiche Bowl mit gesunden Fetten.",
    calories: 390, protein: 30, carbs: 28, fat: 18,
    duration: 15, servings: 1,
    tags: ["High-Protein", "Low-Carb", "Abendessen", "Schnell"],
    ingredients: [
      { name: "Garnelen", amount: "180g" },
      { name: "Avocado", amount: "½ Stück" },
      { name: "Brauner Reis (trocken)", amount: "60g" },
      { name: "Limettensaft", amount: "1 EL" },
      { name: "Olivenöl", amount: "1 EL" },
      { name: "Sriracha", amount: "nach Geschmack" },
      { name: "Sesamkörner", amount: "1 TL" },
    ],
    steps: [
      "Reis kochen.",
      "Garnelen in Olivenöl 2 Min pro Seite braten.",
      "Avocado in Scheiben schneiden.",
      "Bowl aufbauen: Reis, Garnelen, Avocado.",
      "Mit Limettensaft, Sriracha und Sesam anrichten.",
    ],
  },
];
